<?xml version="1.0" encoding='utf-8'?>

<!--
	verbs-ro.xml - List of Romanian verbs with their conjugation template.
	The templates were generated by Ars-Linguistica using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.

	Copyright (C) 2018 Ars-Linguistica <https://github.com/Ars-Linguistica>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE conjugation-ro [
    <!ELEMENT conjugation-ro (template)+>
    <!ATTLIST conjugation-ro
      xmlns CDATA #FIXED ''>

    <!ELEMENT template (Prezent,Imperfect,Conjunctiv,Infinitiv,
                        (Perfect,Mai,Viitor,Conditional,Imperativ,Gerunziu,
                         Participiu)?)>
    <!ATTLIST template
      xmlns CDATA #FIXED ''
      name NMTOKEN #REQUIRED>

    <!ELEMENT Prezent (Prezent-Prezent)>
    <!ATTLIST Prezent
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperfect (Imperfect-Imperfect)>
    <!ATTLIST Imperfect
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjunctiv (Conjunctiv-prezent,Conjunctiv-perfect?)>
    <!ATTLIST Conjunctiv
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitiv (Infinitiv-Afirmativ)>
    <!ATTLIST Infinitiv
      xmlns CDATA #FIXED ''>

    <!ELEMENT Perfect (Perfect-simplu,Perfect-compus)>
    <!ATTLIST Perfect
      xmlns CDATA #FIXED ''>

    <!ELEMENT Mai (Mai-mult-ca-perfect)>
    <!ATTLIST Mai
      xmlns CDATA #FIXED ''>

    <!ELEMENT Viitor (Viitor-I,Viitor-I-popular,Viitor-II,
                      Viitor-II-popular)>
    <!ATTLIST Viitor
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conditional (Conditional-prezent,Conditional-perfect)>
    <!ATTLIST Conditional
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativ (Imperativ-Imperativ,Imperativ-Negativ)>
    <!ATTLIST Imperativ
      xmlns CDATA #FIXED ''>

    <!ELEMENT Gerunziu (Gerunziu-Gerunziu)>
    <!ATTLIST Gerunziu
      xmlns CDATA #FIXED ''>

    <!ELEMENT Participiu (Participiu-Participiu)>
    <!ATTLIST Participiu
      xmlns CDATA #FIXED ''>

    <!ELEMENT Prezent-Prezent (p)+>
    <!ATTLIST Prezent-Prezent
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperfect-Imperfect (p)+>
    <!ATTLIST Imperfect-Imperfect
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjunctiv-prezent (p)+>
    <!ATTLIST Conjunctiv-prezent
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjunctiv-perfect (p)+>
    <!ATTLIST Conjunctiv-perfect
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitiv-Afirmativ (p)>
    <!ATTLIST Infinitiv-Afirmativ
      xmlns CDATA #FIXED ''>

    <!ELEMENT Perfect-simplu (p)+>
    <!ATTLIST Perfect-simplu
      xmlns CDATA #FIXED ''>

    <!ELEMENT Perfect-compus (p)+>
    <!ATTLIST Perfect-compus
      xmlns CDATA #FIXED ''>

    <!ELEMENT Mai-mult-ca-perfect (p)+>
    <!ATTLIST Mai-mult-ca-perfect
      xmlns CDATA #FIXED ''>

    <!ELEMENT Viitor-I (p)+>
    <!ATTLIST Viitor-I
      xmlns CDATA #FIXED ''>

    <!ELEMENT Viitor-I-popular (p)+>
    <!ATTLIST Viitor-I-popular
      xmlns CDATA #FIXED ''>

    <!ELEMENT Viitor-II (p)+>
    <!ATTLIST Viitor-II
      xmlns CDATA #FIXED ''>

    <!ELEMENT Viitor-II-popular (p)+>
    <!ATTLIST Viitor-II-popular
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conditional-prezent (p)+>
    <!ATTLIST Conditional-prezent
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conditional-perfect (p)+>
    <!ATTLIST Conditional-perfect
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativ-Imperativ (p)+>
    <!ATTLIST Imperativ-Imperativ
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativ-Negativ (p)+>
    <!ATTLIST Imperativ-Negativ
      xmlns CDATA #FIXED ''>

    <!ELEMENT Gerunziu-Gerunziu (p)>
    <!ATTLIST Gerunziu-Gerunziu
      xmlns CDATA #FIXED ''>

    <!ELEMENT Participiu-Participiu (p)>
    <!ATTLIST Participiu-Participiu
      xmlns CDATA #FIXED ''>

    <!ELEMENT p (i)>
    <!ATTLIST p
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>
    <!ATTLIST i
      xmlns CDATA #FIXED ''>
]>

<conjugation-ro>

<template name="a:vea">
	<Prezent>
		<Prezent-Prezent>
			<p><i>m</i></p>
			<p><i>i</i></p>
			<p><i></i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>u</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>veam</i></p>
			<p><i>veai</i></p>
			<p><i>vea</i></p>
			<p><i>veam</i></p>
			<p><i>veaţ</i></p>
			<p><i>veau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>ș</i></p>
			<p><i>i</i></p>
			<p><i>r</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>r</i></p>
		</Conjunctiv-prezent>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>vea</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
</template>

<template name="b:ea">
	<Prezent>
		<Prezent-Prezent>
			<p><i>eau</i></p>
			<p><i>ei</i></p>
			<p><i>ea</i></p>
			<p><i>em</i></p>
			<p><i>eţi</i></p>
			<p><i>eau</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>eam</i></p>
			<p><i>eai</i></p>
			<p><i>ea</i></p>
			<p><i>eam</i></p>
			<p><i>eaţi</i></p>
			<p><i>eau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>eau</i></p>
			<p><i>ei</i></p>
			<p><i>eie</i></p>
			<p><i>em</i></p>
			<p><i>eţi</i></p>
			<p><i>eie</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>ea</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>ăui</i></p>
			<p><i>ăuși</i></p>
			<p><i>ău</i></p>
			<p><i>ăurăm</i></p>
			<p><i>ăurăţi</i></p>
			<p><i>ăură</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>ăusem</i></p>
			<p><i>ăuseși</i></p>
			<p><i>ăuse</i></p>
			<p><i>ăuserăm</i></p>
			<p><i>ăuserăţi</i></p>
			<p><i>ăuseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>eau</i></p>
			<p><i>ei</i></p>
			<p><i>eie</i></p>
			<p><i>em</i></p>
			<p><i>eţi</i></p>
			<p><i>eie</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>eau</i></p>
			<p><i>ei</i></p>
			<p><i>eie</i></p>
			<p><i>em</i></p>
			<p><i>eţi</i></p>
			<p><i>eie</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>ea</i></p>
			<p><i>eţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i>ea</i></p>
			<p><i>eţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>ând</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>ăut</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name="ce:re">
	<Prezent>
		<Prezent-Prezent>
			<p><i>r</i></p>
			<p><i>ri</i></p>
			<p><i>re</i></p>
			<p><i>rem</i></p>
			<p><i>reţi</i></p>
			<p><i>r</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>ream</i></p>
			<p><i>reai</i></p>
			<p><i>rea</i></p>
			<p><i>ream</i></p>
			<p><i>reaţi</i></p>
			<p><i>reau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>r</i></p>
			<p><i>ri</i></p>
			<p><i>ară</i></p>
			<p><i>rem</i></p>
			<p><i>reţi</i></p>
			<p><i>ară</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>re</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>rui</i></p>
			<p><i>ruși</i></p>
			<p><i>ru</i></p>
			<p><i>rurăm</i></p>
			<p><i>rurăţi</i></p>
			<p><i>rură</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>rusem</i></p>
			<p><i>ruseși</i></p>
			<p><i>ruse</i></p>
			<p><i>ruserăm</i></p>
			<p><i>ruserăţi</i></p>
			<p><i>ruseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>r</i></p>
			<p><i>ri</i></p>
			<p><i>ară</i></p>
			<p><i>rem</i></p>
			<p><i>reţi</i></p>
			<p><i>ară</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>r</i></p>
			<p><i>ri</i></p>
			<p><i>ară</i></p>
			<p><i>rem</i></p>
			<p><i>reţi</i></p>
			<p><i>ară</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>re</i></p>
			<p><i>reţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i>re</i></p>
			<p><i>reţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>rând</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>rut</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name="d:a">
	<Prezent>
		<Prezent-Prezent>
			<p><i>au</i></p>
			<p><i>ai</i></p>
			<p><i>ă</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>au</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>ădeam</i></p>
			<p><i>ădeai</i></p>
			<p><i>ădea</i></p>
			<p><i>ădeam</i></p>
			<p><i>ădeaţi</i></p>
			<p><i>ădeau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>au</i></p>
			<p><i>ai</i></p>
			<p><i>ea</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>ea</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>a</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>ădui</i></p>
			<p><i>ăduși</i></p>
			<p><i>ădu</i></p>
			<p><i>ădurăm</i></p>
			<p><i>ădurăţi</i></p>
			<p><i>ădură</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>ădusem</i></p>
			<p><i>ăduseși</i></p>
			<p><i>ăduse</i></p>
			<p><i>ăduserăm</i></p>
			<p><i>ăduserăţi</i></p>
			<p><i>ăduseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>au</i></p>
			<p><i>ai</i></p>
			<p><i>ea</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>ea</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>au</i></p>
			<p><i>ai</i></p>
			<p><i>ea</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>ea</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>ă</i></p>
			<p><i>aţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i>a</i></p>
			<p><i>aţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>ând</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>at</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name="dans:a">
	<Prezent>
		<Prezent-Prezent>
			<p><i>ez</i></p>
			<p><i>ezi</i></p>
			<p><i>ează</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>ează</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>am</i></p>
			<p><i>ai</i></p>
			<p><i>a</i></p>
			<p><i>am</i></p>
			<p><i>aţi</i></p>
			<p><i>au</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>ez</i></p>
			<p><i>ezi</i></p>
			<p><i>eze</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>eze</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>a</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>ai</i></p>
			<p><i>ași</i></p>
			<p><i>ă</i></p>
			<p><i>arăm</i></p>
			<p><i>arăţi</i></p>
			<p><i>ară</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>asem</i></p>
			<p><i>aseși</i></p>
			<p><i>ase</i></p>
			<p><i>aserăm</i></p>
			<p><i>aserăţi</i></p>
			<p><i>aseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>ez</i></p>
			<p><i>ezi</i></p>
			<p><i>eze</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>eze</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>ez</i></p>
			<p><i>ezi</i></p>
			<p><i>eze</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>eze</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>ează</i></p>
			<p><i>aţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i>a</i></p>
			<p><i>aţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>ând</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>at</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name="do:rmi">
	<Prezent>
		<Prezent-Prezent>
			<p><i>rm</i></p>
			<p><i>rmi</i></p>
			<p><i>arme</i></p>
			<p><i>rmim</i></p>
			<p><i>rmiţi</i></p>
			<p><i>rm</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>rmeam</i></p>
			<p><i>rmeai</i></p>
			<p><i>rmea</i></p>
			<p><i>rmeam</i></p>
			<p><i>rmeaţi</i></p>
			<p><i>rmeau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>rm</i></p>
			<p><i>rmi</i></p>
			<p><i>armă</i></p>
			<p><i>rmim</i></p>
			<p><i>rmiţi</i></p>
			<p><i>armă</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>rmi</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>rmii</i></p>
			<p><i>rmiși</i></p>
			<p><i>rmi</i></p>
			<p><i>rmirăm</i></p>
			<p><i>rmirăţi</i></p>
			<p><i>rmiră</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>rmisem</i></p>
			<p><i>rmiseși</i></p>
			<p><i>rmise</i></p>
			<p><i>rmiserăm</i></p>
			<p><i>rmiserăţi</i></p>
			<p><i>rmiseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>rm</i></p>
			<p><i>rmi</i></p>
			<p><i>armă</i></p>
			<p><i>rmim</i></p>
			<p><i>rmiţi</i></p>
			<p><i>armă</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>rm</i></p>
			<p><i>rmi</i></p>
			<p><i>armă</i></p>
			<p><i>rmim</i></p>
			<p><i>rmiţi</i></p>
			<p><i>armă</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>rmi</i></p>
			<p><i>rmiţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i>rmi</i></p>
			<p><i>rmiţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>rmind</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>rmit</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name="fer:i">
	<Prezent>
		<Prezent-Prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ește</i></p>
			<p><i>im</i></p>
			<p><i>iţi</i></p>
			<p><i>esc</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>eam</i></p>
			<p><i>eai</i></p>
			<p><i>ea</i></p>
			<p><i>eam</i></p>
			<p><i>eaţi</i></p>
			<p><i>eau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ească</i></p>
			<p><i>im</i></p>
			<p><i>iţi</i></p>
			<p><i>ească</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>i</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>ii</i></p>
			<p><i>iși</i></p>
			<p><i>i</i></p>
			<p><i>irăm</i></p>
			<p><i>irăţi</i></p>
			<p><i>iră</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>isem</i></p>
			<p><i>iseși</i></p>
			<p><i>ise</i></p>
			<p><i>iserăm</i></p>
			<p><i>iserăţi</i></p>
			<p><i>iseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ească</i></p>
			<p><i>im</i></p>
			<p><i>iţi</i></p>
			<p><i>ească</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ească</i></p>
			<p><i>im</i></p>
			<p><i>iţi</i></p>
			<p><i>ească</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>ește</i></p>
			<p><i>iţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i>i</i></p>
			<p><i>iţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>ind</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>it</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name=":fi">
	<Prezent>
		<Prezent-Prezent>
			<p><i>sunt</i></p>
			<p><i>ești</i></p>
			<p><i>e</i></p>
			<p><i>suntem</i></p>
			<p><i>sunteţi</i></p>
			<p><i>sunt</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>eram</i></p>
			<p><i>erai</i></p>
			<p><i>era</i></p>
			<p><i>eram</i></p>
			<p><i>eraţi</i></p>
			<p><i>erau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>fiu</i></p>
			<p><i>fii</i></p>
			<p><i>fie</i></p>
			<p><i>fim</i></p>
			<p><i>fiţi</i></p>
			<p><i>fie</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>fi</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>fui</i></p>
			<p><i>fuși</i></p>
			<p><i>fu</i></p>
			<p><i>furăm</i></p>
			<p><i>furăţi</i></p>
			<p><i>fură</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>fusesem</i></p>
			<p><i>fuseseși</i></p>
			<p><i>fusese</i></p>
			<p><i>fuseserăm</i></p>
			<p><i>fuseserăţi</i></p>
			<p><i>fuseseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>fiu</i></p>
			<p><i>fii</i></p>
			<p><i>fie</i></p>
			<p><i>fim</i></p>
			<p><i>fiţi</i></p>
			<p><i>fie</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>fiu</i></p>
			<p><i>fii</i></p>
			<p><i>fie</i></p>
			<p><i>fim</i></p>
			<p><i>fiţi</i></p>
			<p><i>fie</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>fii</i></p>
			<p><i>fiţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i>fi</i></p>
			<p><i>fiţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>fiind</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>fost</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name="locui:">
	<Prezent>
		<Prezent-Prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ește</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>esc</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>am</i></p>
			<p><i>ai</i></p>
			<p><i>a</i></p>
			<p><i>am</i></p>
			<p><i>aţi</i></p>
			<p><i>au</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ască</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>ască</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i></i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>i</i></p>
			<p><i>și</i></p>
			<p><i></i></p>
			<p><i>răm</i></p>
			<p><i>răţi</i></p>
			<p><i>ră</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>sem</i></p>
			<p><i>seși</i></p>
			<p><i>se</i></p>
			<p><i>serăm</i></p>
			<p><i>serăţi</i></p>
			<p><i>seră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</Viitor-I>
		<Viitor-I-popular>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ască</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>ască</i></p>
		</Viitor-I-popular>
		<Viitor-II>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
		</Viitor-II>
		<Viitor-II-popular>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ască</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>ască</i></p>
		</Viitor-II-popular>
	</Viitor>
	<Conditional>
		<Conditional-prezent>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</Conditional-prezent>
		<Conditional-perfect>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
		</Conditional-perfect>
	</Conditional>
	<Imperativ>
		<Imperativ-Imperativ>
			<p><i>ește</i></p>
			<p><i>ţi</i></p>
		</Imperativ-Imperativ>
		<Imperativ-Negativ>
			<p><i></i></p>
			<p><i>ţi</i></p>
		</Imperativ-Negativ>
	</Imperativ>
	<Gerunziu>
		<Gerunziu-Gerunziu>
			<p><i>nd</i></p>
		</Gerunziu-Gerunziu>
	</Gerunziu>
	<Participiu>
		<Participiu-Participiu>
			<p><i>t</i></p>
		</Participiu-Participiu>
	</Participiu>
</template>

<template name=":lua">
	<Prezent>
		<Prezent-Prezent>
			<p><i>iau</i></p>
			<p><i>iei</i></p>
			<p><i>ia</i></p>
			<p><i>luăm</i></p>
			<p><i>luaţi</i></p>
			<p><i>iau</i></p>
		</Prezent-Prezent>
	</Prezent>
	<Imperfect>
		<Imperfect-Imperfect>
			<p><i>luam</i></p>
			<p><i>luai</i></p>
			<p><i>lua</i></p>
			<p><i>luam</i></p>
			<p><i>luaţi</i></p>
			<p><i>luau</i></p>
		</Imperfect-Imperfect>
	</Imperfect>
	<Conjunctiv>
		<Conjunctiv-prezent>
			<p><i>iau</i></p>
			<p><i>iei</i></p>
			<p><i>ia</i></p>
			<p><i>luăm</i></p>
			<p><i>luaţi</i></p>
			<p><i>ia</i></p>
		</Conjunctiv-prezent>
		<Conjunctiv-perfect>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
		</Conjunctiv-perfect>
	</Conjunctiv>
	<Infinitiv>
		<Infinitiv-Afirmativ>
			<p><i>lua</i></p>
		</Infinitiv-Afirmativ>
	</Infinitiv>
	<Perfect>
		<Perfect-simplu>
			<p><i>luai</i></p>
			<p><i>luași</i></p>
			<p><i>luă</i></p>
			<p><i>luarăm</i></p>
			<p><i>luarăţi</i></p>
			<p><i>luară</i></p>
		</Perfect-simplu>
		<Perfect-compus>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
		</Perfect-compus>
	</Perfect>
	<Mai>
		<Mai-mult-ca-perfect>
			<p><i>luasem</i></p>
			<p><i>luaseși</i></p>
			<p><i>luase</i></p>
			<p><i>luaserăm</i></p>
			<p><i>luaserăţi</i></p>
			<p><i>luaseră</i></p>
		</Mai-mult-ca-perfect>
	</Mai>
	<Viitor>
		<Viitor-I>
			<p><i>lua</i></p>