<?xml version="1.0" encoding='utf-8'?>

<!--
	conjugation-pt.xml - List of Portuguese conjugation templates.
	The templates were generated by Ars-Linguistica using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.

	Copyright (C) 2018 Ars-Linguistica <https://github.com/Ars-Linguistica>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE conjugation-pt [
    <!ELEMENT conjugation-pt (template)+>
    <!ATTLIST conjugation-pt
      xmlns CDATA #FIXED ''>

    <!ELEMENT template (Indicativo,Condicional,Conjuntivo,Infinitivo,
                        Imperativo,Gerúndio,Particípio)>
    <!ATTLIST template
      xmlns CDATA #FIXED ''
      name NMTOKEN #REQUIRED>

    <!ELEMENT Indicativo (Indicativo-presente,
                          Indicativo-Pretérito-Perfeito-Composto,
                          Indicativo-pretérito-imperfeito,
                          Indicativo-Pretérito-Mais-que-Perfeito-Composto,
                          Indicativo-Pretérito-Mais-que-Perfeito-Simples,
                          Indicativo-pretérito-perfeito-simples,
                          Indicativo-Pretérito-Mais-que-Perfeito-Anterior,
                          Indicativo-Futuro-do-Presente-Simples,
                          Indicativo-Futuro-do-Presente-Composto)>
    <!ATTLIST Indicativo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Condicional (Condicional-Futuro-do-Pretérito-Simples,
                           Condicional-Futuro-do-Pretérito-Composto)>
    <!ATTLIST Condicional
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjuntivo (Conjuntivo--Subjuntivo-Presente,
                          Conjuntivo--Subjuntivo-Pretérito-Perfeito,
                          Conjuntivo--Subjuntivo-Pretérito-Imperfeito,
                          Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito,
                          Conjuntivo--Subjuntivo-Futuro-Simples,
                          Conjuntivo--Subjuntivo-Futuro-Composto)>
    <!ATTLIST Conjuntivo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitivo (Infinitivo-Pessoal-Presente,
                          Infinitivo-Pessoal-Pretérito,
                          Infinitivo-Infinitivo)>
    <!ATTLIST Infinitivo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativo (Imperativo-Afirmativo,Imperativo-Negativo)>
    <!ATTLIST Imperativo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Gerúndio (Gerúndio-Gerúndio)>
    <!ATTLIST Gerúndio
      xmlns CDATA #FIXED ''>

    <!ELEMENT Particípio (Particípio-Particípio)>
    <!ATTLIST Particípio
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-presente (p)+>
    <!ATTLIST Indicativo-presente
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Pretérito-Perfeito-Composto (p)+>
    <!ATTLIST Indicativo-Pretérito-Perfeito-Composto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-pretérito-imperfeito (p)+>
    <!ATTLIST Indicativo-pretérito-imperfeito
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Pretérito-Mais-que-Perfeito-Composto (p)+>
    <!ATTLIST Indicativo-Pretérito-Mais-que-Perfeito-Composto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Pretérito-Mais-que-Perfeito-Simples (p)+>
    <!ATTLIST Indicativo-Pretérito-Mais-que-Perfeito-Simples
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-pretérito-perfeito-simples (p)+>
    <!ATTLIST Indicativo-pretérito-perfeito-simples
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Pretérito-Mais-que-Perfeito-Anterior (p)+>
    <!ATTLIST Indicativo-Pretérito-Mais-que-Perfeito-Anterior
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Futuro-do-Presente-Simples (p)+>
    <!ATTLIST Indicativo-Futuro-do-Presente-Simples
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Futuro-do-Presente-Composto (p)+>
    <!ATTLIST Indicativo-Futuro-do-Presente-Composto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Condicional-Futuro-do-Pretérito-Simples (p)+>
    <!ATTLIST Condicional-Futuro-do-Pretérito-Simples
      xmlns CDATA #FIXED ''>

    <!ELEMENT Condicional-Futuro-do-Pretérito-Composto (p)+>
    <!ATTLIST Condicional-Futuro-do-Pretérito-Composto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjuntivo--Subjuntivo-Presente (p)+>
    <!ATTLIST Conjuntivo--Subjuntivo-Presente
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjuntivo--Subjuntivo-Pretérito-Perfeito (p)+>
    <!ATTLIST Conjuntivo--Subjuntivo-Pretérito-Perfeito
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjuntivo--Subjuntivo-Pretérito-Imperfeito (p)+>
    <!ATTLIST Conjuntivo--Subjuntivo-Pretérito-Imperfeito
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito (p)+>
    <!ATTLIST Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjuntivo--Subjuntivo-Futuro-Simples (p)+>
    <!ATTLIST Conjuntivo--Subjuntivo-Futuro-Simples
      xmlns CDATA #FIXED ''>

    <!ELEMENT Conjuntivo--Subjuntivo-Futuro-Composto (p)+>
    <!ATTLIST Conjuntivo--Subjuntivo-Futuro-Composto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitivo-Pessoal-Presente (p)+>
    <!ATTLIST Infinitivo-Pessoal-Presente
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitivo-Pessoal-Pretérito (p)+>
    <!ATTLIST Infinitivo-Pessoal-Pretérito
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitivo-Infinitivo (p)+>
    <!ATTLIST Infinitivo-Infinitivo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativo-Afirmativo (p)+>
    <!ATTLIST Imperativo-Afirmativo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativo-Negativo (p)+>
    <!ATTLIST Imperativo-Negativo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Gerúndio-Gerúndio (p)+>
    <!ATTLIST Gerúndio-Gerúndio
      xmlns CDATA #FIXED ''>

    <!ELEMENT Particípio-Particípio (p)>
    <!ATTLIST Particípio-Particípio
      xmlns CDATA #FIXED ''>

    <!ELEMENT p (i)>
    <!ATTLIST p
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>
    <!ATTLIST i
      xmlns CDATA #FIXED ''>
]>

<conjugation-pt>

<template name="aque:cer">
	<Indicativo>
		<Indicativo-presente>
			<p><i>ço</i></p>
			<p><i>ces</i></p>
			<p><i>ce</i></p>
			<p><i>cemos</i></p>
			<p><i>ceis</i></p>
			<p><i>cem</i></p>
		</Indicativo-presente>
		<Indicativo-Pretérito-Perfeito-Composto>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Indicativo-Pretérito-Perfeito-Composto>
		<Indicativo-pretérito-imperfeito>
			<p><i>cia</i></p>
			<p><i>cias</i></p>
			<p><i>cia</i></p>
			<p><i>cíamos</i></p>
			<p><i>cíeis</i></p>
			<p><i>ciam</i></p>
		</Indicativo-pretérito-imperfeito>
		<Indicativo-Pretérito-Mais-que-Perfeito-Composto>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Composto>
		<Indicativo-Pretérito-Mais-que-Perfeito-Simples>
			<p><i>cera</i></p>
			<p><i>ceras</i></p>
			<p><i>cera</i></p>
			<p><i>cêramos</i></p>
			<p><i>cêreis</i></p>
			<p><i>ceram</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Simples>
		<Indicativo-pretérito-perfeito-simples>
			<p><i>ci</i></p>
			<p><i>ceste</i></p>
			<p><i>ceu</i></p>
			<p><i>cemos</i></p>
			<p><i>cestes</i></p>
			<p><i>ceram</i></p>
		</Indicativo-pretérito-perfeito-simples>
		<Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
		<Indicativo-Futuro-do-Presente-Simples>
			<p><i>cerei</i></p>
			<p><i>cerás</i></p>
			<p><i>cerá</i></p>
			<p><i>ceremos</i></p>
			<p><i>cereis</i></p>
			<p><i>cerão</i></p>
		</Indicativo-Futuro-do-Presente-Simples>
		<Indicativo-Futuro-do-Presente-Composto>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Indicativo-Futuro-do-Presente-Composto>
	</Indicativo>
	<Condicional>
		<Condicional-Futuro-do-Pretérito-Simples>
			<p><i>ceria</i></p>
			<p><i>cerias</i></p>
			<p><i>ceria</i></p>
			<p><i>ceríamos</i></p>
			<p><i>ceríeis</i></p>
			<p><i>ceriam</i></p>
		</Condicional-Futuro-do-Pretérito-Simples>
		<Condicional-Futuro-do-Pretérito-Composto>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Condicional-Futuro-do-Pretérito-Composto>
	</Condicional>
	<Conjuntivo>
		<Conjuntivo--Subjuntivo-Presente>
			<p><i>ça</i></p>
			<p><i>ças</i></p>
			<p><i>ça</i></p>
			<p><i>çamos</i></p>
			<p><i>çais</i></p>
			<p><i>çam</i></p>
		</Conjuntivo--Subjuntivo-Presente>
		<Conjuntivo--Subjuntivo-Pretérito-Perfeito>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Perfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
			<p><i>cesse</i></p>
			<p><i>cesses</i></p>
			<p><i>cesse</i></p>
			<p><i>cêssemos</i></p>
			<p><i>cêsseis</i></p>
			<p><i>cessem</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
		<Conjuntivo--Subjuntivo-Futuro-Simples>
			<p><i>cer</i></p>
			<p><i>ceres</i></p>
			<p><i>cer</i></p>
			<p><i>cermos</i></p>
			<p><i>cerdes</i></p>
			<p><i>cerem</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Simples>
		<Conjuntivo--Subjuntivo-Futuro-Composto>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Composto>
	</Conjuntivo>
	<Infinitivo>
		<Infinitivo-Pessoal-Presente>
			<p><i>cer</i></p>
			<p><i>ceres</i></p>
			<p><i>cer</i></p>
			<p><i>cermos</i></p>
			<p><i>cerdes</i></p>
			<p><i>cerem</i></p>
		</Infinitivo-Pessoal-Presente>
		<Infinitivo-Pessoal-Pretérito>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
			<p><i>cido</i></p>
		</Infinitivo-Pessoal-Pretérito>
		<Infinitivo-Infinitivo>
			<p><i>cer</i></p>
			<p><i>cido</i></p>
		</Infinitivo-Infinitivo>
	</Infinitivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>-</i></p>
			<p><i>ce</i></p>
			<p><i>ça</i></p>
			<p><i>çamos</i></p>
			<p><i>cei</i></p>
			<p><i>çam</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-Negativo>
			<p><i>-</i></p>
			<p><i>ças</i></p>
			<p><i>ça</i></p>
			<p><i>çamos</i></p>
			<p><i>çais</i></p>
			<p><i>çam</i></p>
		</Imperativo-Negativo>
	</Imperativo>
	<Gerúndio>
		<Gerúndio-Gerúndio>
			<p><i>cendo</i></p>
			<p><i>cido</i></p>
		</Gerúndio-Gerúndio>
	</Gerúndio>
	<Particípio>
		<Particípio-Particípio>
			<p><i>cido</i></p>
		</Particípio-Particípio>
	</Particípio>
</template>

<template name="ac:udir">
	<Indicativo>
		<Indicativo-presente>
			<p><i>udo</i></p>
			<p><i>odes</i></p>
			<p><i>ode</i></p>
			<p><i>udimos</i></p>
			<p><i>udis</i></p>
			<p><i>odem</i></p>
		</Indicativo-presente>
		<Indicativo-Pretérito-Perfeito-Composto>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Indicativo-Pretérito-Perfeito-Composto>
		<Indicativo-pretérito-imperfeito>
			<p><i>udia</i></p>
			<p><i>udias</i></p>
			<p><i>udia</i></p>
			<p><i>udíamos</i></p>
			<p><i>udíeis</i></p>
			<p><i>udiam</i></p>
		</Indicativo-pretérito-imperfeito>
		<Indicativo-Pretérito-Mais-que-Perfeito-Composto>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Composto>
		<Indicativo-Pretérito-Mais-que-Perfeito-Simples>
			<p><i>udira</i></p>
			<p><i>udiras</i></p>
			<p><i>udira</i></p>
			<p><i>udíramos</i></p>
			<p><i>udíreis</i></p>
			<p><i>udiram</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Simples>
		<Indicativo-pretérito-perfeito-simples>
			<p><i>udi</i></p>
			<p><i>udiste</i></p>
			<p><i>udiu</i></p>
			<p><i>udimos</i></p>
			<p><i>udistes</i></p>
			<p><i>udiram</i></p>
		</Indicativo-pretérito-perfeito-simples>
		<Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
		<Indicativo-Futuro-do-Presente-Simples>
			<p><i>udirei</i></p>
			<p><i>udirás</i></p>
			<p><i>udirá</i></p>
			<p><i>udiremos</i></p>
			<p><i>udireis</i></p>
			<p><i>udirão</i></p>
		</Indicativo-Futuro-do-Presente-Simples>
		<Indicativo-Futuro-do-Presente-Composto>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Indicativo-Futuro-do-Presente-Composto>
	</Indicativo>
	<Condicional>
		<Condicional-Futuro-do-Pretérito-Simples>
			<p><i>udiria</i></p>
			<p><i>udirias</i></p>
			<p><i>udiria</i></p>
			<p><i>udiríamos</i></p>
			<p><i>udiríeis</i></p>
			<p><i>udiriam</i></p>
		</Condicional-Futuro-do-Pretérito-Simples>
		<Condicional-Futuro-do-Pretérito-Composto>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Condicional-Futuro-do-Pretérito-Composto>
	</Condicional>
	<Conjuntivo>
		<Conjuntivo--Subjuntivo-Presente>
			<p><i>uda</i></p>
			<p><i>udas</i></p>
			<p><i>uda</i></p>
			<p><i>udamos</i></p>
			<p><i>udais</i></p>
			<p><i>udam</i></p>
		</Conjuntivo--Subjuntivo-Presente>
		<Conjuntivo--Subjuntivo-Pretérito-Perfeito>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Perfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
			<p><i>udisse</i></p>
			<p><i>udisses</i></p>
			<p><i>udisse</i></p>
			<p><i>udíssemos</i></p>
			<p><i>udísseis</i></p>
			<p><i>udissem</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
		<Conjuntivo--Subjuntivo-Futuro-Simples>
			<p><i>udir</i></p>
			<p><i>udires</i></p>
			<p><i>udir</i></p>
			<p><i>udirmos</i></p>
			<p><i>udirdes</i></p>
			<p><i>udirem</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Simples>
		<Conjuntivo--Subjuntivo-Futuro-Composto>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Composto>
	</Conjuntivo>
	<Infinitivo>
		<Infinitivo-Pessoal-Presente>
			<p><i>udir</i></p>
			<p><i>udires</i></p>
			<p><i>udir</i></p>
			<p><i>udirmos</i></p>
			<p><i>udirdes</i></p>
			<p><i>udirem</i></p>
		</Infinitivo-Pessoal-Presente>
		<Infinitivo-Pessoal-Pretérito>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
			<p><i>udido</i></p>
		</Infinitivo-Pessoal-Pretérito>
		<Infinitivo-Infinitivo>
			<p><i>udir</i></p>
			<p><i>udido</i></p>
		</Infinitivo-Infinitivo>
	</Infinitivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>-</i></p>
			<p><i>ode</i></p>
			<p><i>uda</i></p>
			<p><i>udamos</i></p>
			<p><i>udi</i></p>
			<p><i>udam</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-Negativo>
			<p><i>-</i></p>
			<p><i>udas</i></p>
			<p><i>uda</i></p>
			<p><i>udamos</i></p>
			<p><i>udais</i></p>
			<p><i>udam</i></p>
		</Imperativo-Negativo>
	</Imperativo>
	<Gerúndio>
		<Gerúndio-Gerúndio>
			<p><i>udindo</i></p>
			<p><i>udido</i></p>
		</Gerúndio-Gerúndio>
	</Gerúndio>
	<Particípio>
		<Particípio-Particípio>
			<p><i>udido</i></p>
		</Particípio-Particípio>
	</Particípio>
</template>

<template name="adeq:uar">
	<Indicativo>
		<Indicativo-presente>
			<p><i>uo</i></p>
			<p><i>uas</i></p>
			<p><i>ua</i></p>
			<p><i>uamos</i></p>
			<p><i>uais</i></p>
			<p><i>uam</i></p>
		</Indicativo-presente>
		<Indicativo-Pretérito-Perfeito-Composto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-Pretérito-Perfeito-Composto>
		<Indicativo-pretérito-imperfeito>
			<p><i>uava</i></p>
			<p><i>uavas</i></p>
			<p><i>uava</i></p>
			<p><i>uávamos</i></p>
			<p><i>uáveis</i></p>
			<p><i>uavam</i></p>
		</Indicativo-pretérito-imperfeito>
		<Indicativo-Pretérito-Mais-que-Perfeito-Composto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Composto>
		<Indicativo-Pretérito-Mais-que-Perfeito-Simples>
			<p><i>uara</i></p>
			<p><i>uaras</i></p>
			<p><i>uara</i></p>
			<p><i>uáramos</i></p>
			<p><i>uáreis</i></p>
			<p><i>uaram</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Simples>
		<Indicativo-pretérito-perfeito-simples>
			<p><i>uei</i></p>
			<p><i>uaste</i></p>
			<p><i>uou</i></p>
			<p><i></i></p>
			<p><i>uastes</i></p>
			<p><i>uaram</i></p>
		</Indicativo-pretérito-perfeito-simples>
		<Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
		<Indicativo-Futuro-do-Presente-Simples>
			<p><i>uarei</i></p>
			<p><i>uarás</i></p>
			<p><i>uará</i></p>
			<p><i>uaremos</i></p>
			<p><i>uareis</i></p>
			<p><i>uarão</i></p>
		</Indicativo-Futuro-do-Presente-Simples>
		<Indicativo-Futuro-do-Presente-Composto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-Futuro-do-Presente-Composto>
	</Indicativo>
	<Condicional>
		<Condicional-Futuro-do-Pretérito-Simples>
			<p><i>uaria</i></p>
			<p><i>uarias</i></p>
			<p><i>uaria</i></p>
			<p><i>uaríamos</i></p>
			<p><i>uaríeis</i></p>
			<p><i>uariam</i></p>
		</Condicional-Futuro-do-Pretérito-Simples>
		<Condicional-Futuro-do-Pretérito-Composto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Condicional-Futuro-do-Pretérito-Composto>
	</Condicional>
	<Conjuntivo>
		<Conjuntivo--Subjuntivo-Presente>
			<p><i>úe</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>ueis</i></p>
			<p><i>úem</i></p>
		</Conjuntivo--Subjuntivo-Presente>
		<Conjuntivo--Subjuntivo-Pretérito-Perfeito>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Perfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
			<p><i>uasse</i></p>
			<p><i>uasses</i></p>
			<p><i>uasse</i></p>
			<p><i>uássemos</i></p>
			<p><i>uásseis</i></p>
			<p><i>uassem</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
		<Conjuntivo--Subjuntivo-Futuro-Simples>
			<p><i>uar</i></p>
			<p><i>uares</i></p>
			<p><i>uar</i></p>
			<p><i>uarmos</i></p>
			<p><i>uardes</i></p>
			<p><i>uarem</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Simples>
		<Conjuntivo--Subjuntivo-Futuro-Composto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Composto>
	</Conjuntivo>
	<Infinitivo>
		<Infinitivo-Pessoal-Presente>
			<p><i>uar</i></p>
			<p><i>uares</i></p>
			<p><i>uar</i></p>
			<p><i>uarmos</i></p>
			<p><i>uardes</i></p>
			<p><i>uarem</i></p>
		</Infinitivo-Pessoal-Presente>
		<Infinitivo-Pessoal-Pretérito>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Infinitivo-Pessoal-Pretérito>
		<Infinitivo-Infinitivo>
			<p><i>uar</i></p>
			<p><i>uado</i></p>
		</Infinitivo-Infinitivo>
	</Infinitivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>-</i></p>
			<p><i>ua</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uai</i></p>
			<p><i>úem</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-Negativo>
			<p><i>-</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>ueis</i></p>
			<p><i>úem</i></p>
		</Imperativo-Negativo>
	</Imperativo>
	<Gerúndio>
		<Gerúndio-Gerúndio>
			<p><i>uando</i></p>
			<p><i>uado</i></p>
		</Gerúndio-Gerúndio>
	</Gerúndio>
	<Particípio>
		<Particípio-Particípio>
			<p><i>uado</i></p>
		</Particípio-Particípio>
	</Particípio>
</template>

<template name="agr:edir">
	<Indicativo>
		<Indicativo-presente>
			<p><i>ido</i></p>
			<p><i>ides</i></p>
			<p><i>ide</i></p>
			<p><i>edimos</i></p>
			<p><i>edis</i></p>
			<p><i>idem</i></p>
		</Indicativo-presente>
		<Indicativo-Pretérito-Perfeito-Composto>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Indicativo-Pretérito-Perfeito-Composto>
		<Indicativo-pretérito-imperfeito>
			<p><i>edia</i></p>
			<p><i>edias</i></p>
			<p><i>edia</i></p>
			<p><i>edíamos</i></p>
			<p><i>edíeis</i></p>
			<p><i>ediam</i></p>
		</Indicativo-pretérito-imperfeito>
		<Indicativo-Pretérito-Mais-que-Perfeito-Composto>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Composto>
		<Indicativo-Pretérito-Mais-que-Perfeito-Simples>
			<p><i>edira</i></p>
			<p><i>ediras</i></p>
			<p><i>edira</i></p>
			<p><i>edíramos</i></p>
			<p><i>edíreis</i></p>
			<p><i>ediram</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Simples>
		<Indicativo-pretérito-perfeito-simples>
			<p><i>edi</i></p>
			<p><i>ediste</i></p>
			<p><i>ediu</i></p>
			<p><i>edimos</i></p>
			<p><i>edistes</i></p>
			<p><i>ediram</i></p>
		</Indicativo-pretérito-perfeito-simples>
		<Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
		<Indicativo-Futuro-do-Presente-Simples>
			<p><i>edirei</i></p>
			<p><i>edirás</i></p>
			<p><i>edirá</i></p>
			<p><i>ediremos</i></p>
			<p><i>edireis</i></p>
			<p><i>edirão</i></p>
		</Indicativo-Futuro-do-Presente-Simples>
		<Indicativo-Futuro-do-Presente-Composto>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Indicativo-Futuro-do-Presente-Composto>
	</Indicativo>
	<Condicional>
		<Condicional-Futuro-do-Pretérito-Simples>
			<p><i>ediria</i></p>
			<p><i>edirias</i></p>
			<p><i>ediria</i></p>
			<p><i>ediríamos</i></p>
			<p><i>ediríeis</i></p>
			<p><i>ediriam</i></p>
		</Condicional-Futuro-do-Pretérito-Simples>
		<Condicional-Futuro-do-Pretérito-Composto>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Condicional-Futuro-do-Pretérito-Composto>
	</Condicional>
	<Conjuntivo>
		<Conjuntivo--Subjuntivo-Presente>
			<p><i>ida</i></p>
			<p><i>idas</i></p>
			<p><i>ida</i></p>
			<p><i>idamos</i></p>
			<p><i>idais</i></p>
			<p><i>idam</i></p>
		</Conjuntivo--Subjuntivo-Presente>
		<Conjuntivo--Subjuntivo-Pretérito-Perfeito>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Perfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
			<p><i>edisse</i></p>
			<p><i>edisses</i></p>
			<p><i>edisse</i></p>
			<p><i>edíssemos</i></p>
			<p><i>edísseis</i></p>
			<p><i>edissem</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Imperfeito>
		<Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Mais-que-Perfeito>
		<Conjuntivo--Subjuntivo-Futuro-Simples>
			<p><i>edir</i></p>
			<p><i>edires</i></p>
			<p><i>edir</i></p>
			<p><i>edirmos</i></p>
			<p><i>edirdes</i></p>
			<p><i>edirem</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Simples>
		<Conjuntivo--Subjuntivo-Futuro-Composto>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Conjuntivo--Subjuntivo-Futuro-Composto>
	</Conjuntivo>
	<Infinitivo>
		<Infinitivo-Pessoal-Presente>
			<p><i>edir</i></p>
			<p><i>edires</i></p>
			<p><i>edir</i></p>
			<p><i>edirmos</i></p>
			<p><i>edirdes</i></p>
			<p><i>edirem</i></p>
		</Infinitivo-Pessoal-Presente>
		<Infinitivo-Pessoal-Pretérito>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
			<p><i>edido</i></p>
		</Infinitivo-Pessoal-Pretérito>
		<Infinitivo-Infinitivo>
			<p><i>edir</i></p>
			<p><i>edido</i></p>
		</Infinitivo-Infinitivo>
	</Infinitivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>-</i></p>
			<p><i>ide</i></p>
			<p><i>ida</i></p>
			<p><i>idamos</i></p>
			<p><i>idi</i></p>
			<p><i>idam</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-Negativo>
			<p><i>-</i></p>
			<p><i>idas</i></p>
			<p><i>ida</i></p>
			<p><i>idamos</i></p>
			<p><i>idais</i></p>
			<p><i>idam</i></p>
		</Imperativo-Negativo>
	</Imperativo>
	<Gerúndio>
		<Gerúndio-Gerúndio>
			<p><i>edindo</i></p>
			<p><i>edido</i></p>
		</Gerúndio-Gerúndio>
	</Gerúndio>
	<Particípio>
		<Particípio-Particípio>
			<p><i>edido</i></p>
		</Particípio-Particípio>
	</Particípio>
</template>

<template name="compr:ar">
	<Indicativo>
		<Indicativo-presente>
			<p><i>o</i></p>
			<p><i>as</i></p>
			<p><i>a</i></p>
			<p><i>amos</i></p>
			<p><i>ais</i></p>
			<p><i>am</i></p>
		</Indicativo-presente>
		<Indicativo-Pretérito-Perfeito-Composto>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
		</Indicativo-Pretérito-Perfeito-Composto>
		<Indicativo-pretérito-imperfeito>
			<p><i>ava</i></p>
			<p><i>avas</i></p>
			<p><i>ava</i></p>
			<p><i>ávamos</i></p>
			<p><i>áveis</i></p>
			<p><i>avam</i></p>
		</Indicativo-pretérito-imperfeito>
		<Indicativo-Pretérito-Mais-que-Perfeito-Composto>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Composto>
		<Indicativo-Pretérito-Mais-que-Perfeito-Simples>
			<p><i>ara</i></p>
			<p><i>aras</i></p>
			<p><i>ara</i></p>
			<p><i>áramos</i></p>
			<p><i>áreis</i></p>
			<p><i>aram</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Simples>
		<Indicativo-pretérito-perfeito-simples>
			<p><i>ei</i></p>
			<p><i>aste</i></p>
			<p><i>ou</i></p>
			<p><i>amos</i></p>
			<p><i>astes</i></p>
			<p><i>aram</i></p>
		</Indicativo-pretérito-perfeito-simples>
		<Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
		</Indicativo-Pretérito-Mais-que-Perfeito-Anterior>
		<Indicativo-Futuro-do-Presente-Simples>
			<p><i>arei</i></p>
			<p><i>arás</i></p>
			<p><i>ará</i></p>
			<p><i>aremos</i></p>
			<p><i>areis</i></p>
			<p><i>arão</i></p>
		</Indicativo-Futuro-do-Presente-Simples>
		<Indicativo-Futuro-do-Presente-Composto>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
		</Indicativo-Futuro-do-Presente-Composto>
	</Indicativo>
	<Condicional>
		<Condicional-Futuro-do-Pretérito-Simples>
			<p><i>aria</i></p>
			<p><i>arias</i></p>
			<p><i>aria</i></p>
			<p><i>aríamos</i></p>
			<p><i>aríeis</i></p>
			<p><i>ariam</i></p>
		</Condicional-Futuro-do-Pretérito-Simples>
		<Condicional-Futuro-do-Pretérito-Composto>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
		</Condicional-Futuro-do-Pretérito-Composto>
	</Condicional>
	<Conjuntivo>
		<Conjuntivo--Subjuntivo-Presente>
			<p><i>e</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>emos</i></p>
			<p><i>eis</i></p>
			<p><i>em</i></p>
		</Conjuntivo--Subjuntivo-Presente>
		<Conjuntivo--Subjuntivo-Pretérito-Perfeito>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
			<p><i>ado</i></p>
		</Conjuntivo--Subjuntivo-Pretérito-Perfeito>