<?xml version="1.0" encoding='utf-8'?>

<!--
	conjugation-es.xml - List of Spanish conjugation templates.
	The templates were generated by Ars-Linguistica using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in verbiste.

	Copyright (C) 2018 Ars-Linguistica <https://github.com/Ars-Linguistica>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE conjugation-es [
    <!ELEMENT conjugation-es (template)+>
    <!ATTLIST conjugation-es
      xmlns CDATA #FIXED ''>

    <!ELEMENT template (Indicativo,Subjuntivo,Imperativo,
                        (Condicional,Infinitivo,Gerundio,Participo)?)>
    <!ATTLIST template
      xmlns CDATA #FIXED ''
      name NMTOKEN #REQUIRED>

    <!ELEMENT Indicativo (Indicativo-Presente,
                          Indicativo-Pretérito-imperfecto,
                          Indicativo-Pretérito-perfecto-compuesto,
                          Indicativo-Pretérito-pluscuamperfecto,
                          Indicativo-Futuro,Indicativo-Futuro-perfecto,
                          (Indicativo-presente,
                           Indicativo-pretérito-perfecto-compuesto,
                           Indicativo-pretérito-imperfecto,
                           Indicativo-pretérito-pluscuamperfecto,
                           Indicativo-pretérito-perfecto-simple,
                           Indicativo-pretérito-anterior,Indicativo-futuro,
                           Indicativo-futuro-perfecto)?)>
    <!ATTLIST Indicativo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo (Subjuntivo-Presente,
                          Subjuntivo-Pretérito-imperfecto-1,
                          Subjuntivo-Pretérito-perfecto,
                          Subjuntivo-Pretérito-pluscuamperfecto-1,
                          Subjuntivo-Futuro,Subjuntivo-Futuro-perfecto,
                          (Subjuntivo-presente,
                           Subjuntivo-pretérito-perfecto,
                           Subjuntivo-pretérito-imperfecto-1,
                           Subjuntivo-pretérito-pluscuamperfecto-1,
                           Subjuntivo-pretérito-imperfecto-2,
                           Subjuntivo-pretérito-pluscuamperfecto-2,
                           Subjuntivo-futuro,Subjuntivo-futuro-perfecto)?)>
    <!ATTLIST Subjuntivo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativo (Imperativo-Afirmativo,Imperativo-non)>
    <!ATTLIST Imperativo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Condicional (Condicional-Condicional,Condicional-perfecto)>
    <!ATTLIST Condicional
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitivo (Infinitivo-Infinitivo)>
    <!ATTLIST Infinitivo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Gerundio (Gerundio-Gerondio)>
    <!ATTLIST Gerundio
      xmlns CDATA #FIXED ''>

    <!ELEMENT Participo (Participo-Participo)>
    <!ATTLIST Participo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Presente (p)+>
    <!ATTLIST Indicativo-Presente
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Pretérito-imperfecto (p)+>
    <!ATTLIST Indicativo-Pretérito-imperfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Pretérito-perfecto-compuesto (p)+>
    <!ATTLIST Indicativo-Pretérito-perfecto-compuesto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Pretérito-pluscuamperfecto (p)+>
    <!ATTLIST Indicativo-Pretérito-pluscuamperfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Futuro (p)+>
    <!ATTLIST Indicativo-Futuro
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-Futuro-perfecto (p)+>
    <!ATTLIST Indicativo-Futuro-perfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-presente (p)+>
    <!ATTLIST Indicativo-presente
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-pretérito-perfecto-compuesto (p)+>
    <!ATTLIST Indicativo-pretérito-perfecto-compuesto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-pretérito-imperfecto (p)+>
    <!ATTLIST Indicativo-pretérito-imperfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-pretérito-pluscuamperfecto (p)+>
    <!ATTLIST Indicativo-pretérito-pluscuamperfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-pretérito-perfecto-simple (p)+>
    <!ATTLIST Indicativo-pretérito-perfecto-simple
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-pretérito-anterior (p)+>
    <!ATTLIST Indicativo-pretérito-anterior
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-futuro (p)+>
    <!ATTLIST Indicativo-futuro
      xmlns CDATA #FIXED ''>

    <!ELEMENT Indicativo-futuro-perfecto (p)+>
    <!ATTLIST Indicativo-futuro-perfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-Presente (p)+>
    <!ATTLIST Subjuntivo-Presente
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-Pretérito-imperfecto-1 (p)+>
    <!ATTLIST Subjuntivo-Pretérito-imperfecto-1
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-Pretérito-perfecto (p)+>
    <!ATTLIST Subjuntivo-Pretérito-perfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-Pretérito-pluscuamperfecto-1 (p)+>
    <!ATTLIST Subjuntivo-Pretérito-pluscuamperfecto-1
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-Futuro (p)+>
    <!ATTLIST Subjuntivo-Futuro
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-Futuro-perfecto (p)+>
    <!ATTLIST Subjuntivo-Futuro-perfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-presente (p)+>
    <!ATTLIST Subjuntivo-presente
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-pretérito-perfecto (p)+>
    <!ATTLIST Subjuntivo-pretérito-perfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-pretérito-imperfecto-1 (p)+>
    <!ATTLIST Subjuntivo-pretérito-imperfecto-1
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-pretérito-pluscuamperfecto-1 (p)+>
    <!ATTLIST Subjuntivo-pretérito-pluscuamperfecto-1
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-pretérito-imperfecto-2 (p)+>
    <!ATTLIST Subjuntivo-pretérito-imperfecto-2
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-pretérito-pluscuamperfecto-2 (p)+>
    <!ATTLIST Subjuntivo-pretérito-pluscuamperfecto-2
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-futuro (p)+>
    <!ATTLIST Subjuntivo-futuro
      xmlns CDATA #FIXED ''>

    <!ELEMENT Subjuntivo-futuro-perfecto (p)+>
    <!ATTLIST Subjuntivo-futuro-perfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativo-Afirmativo (p)+>
    <!ATTLIST Imperativo-Afirmativo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Imperativo-non (p)+>
    <!ATTLIST Imperativo-non
      xmlns CDATA #FIXED ''>

    <!ELEMENT Condicional-Condicional (p)+>
    <!ATTLIST Condicional-Condicional
      xmlns CDATA #FIXED ''>

    <!ELEMENT Condicional-perfecto (p)+>
    <!ATTLIST Condicional-perfecto
      xmlns CDATA #FIXED ''>

    <!ELEMENT Infinitivo-Infinitivo (p)+>
    <!ATTLIST Infinitivo-Infinitivo
      xmlns CDATA #FIXED ''>

    <!ELEMENT Gerundio-Gerondio (p)+>
    <!ATTLIST Gerundio-Gerondio
      xmlns CDATA #FIXED ''>

    <!ELEMENT Participo-Participo (p)>
    <!ATTLIST Participo-Participo
      xmlns CDATA #FIXED ''>

    <!ELEMENT p (i)>
    <!ATTLIST p
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>
    <!ATTLIST i
      xmlns CDATA #FIXED ''>
]>

<conjugation-es>

<template name="abol:ir">
	<Indicativo>
		<Indicativo-Presente>
			<p><i>ía</i></p>
			<p><i>-</i></p>
			<p><i>iste</i></p>
			<p><i>ía</i></p>
			<p><i>imos</i></p>
		</Indicativo-Presente>
		<Indicativo-Pretérito-imperfecto>
			<p><i>-</i></p>
			<p><i>í</i></p>
			<p><i>ías</i></p>
			<p><i>-</i></p>
			<p><i>ió</i></p>
			<p><i>íamos</i></p>
		</Indicativo-Pretérito-imperfecto>
		<Indicativo-Pretérito-perfecto-compuesto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-perfecto-compuesto>
		<Indicativo-Pretérito-pluscuamperfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-pluscuamperfecto>
		<Indicativo-Futuro>
			<p><i>iere</i></p>
			<p><i>irás</i></p>
			<p><i>irías</i></p>
			<p><i>iere</i></p>
			<p><i>iremos</i></p>
		</Indicativo-Futuro>
		<Indicativo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Futuro-perfecto>
	</Indicativo>
	<Subjuntivo>
		<Subjuntivo-Presente>
			<p><i>iera</i></p>
			<p><i>-</i></p>
			<p><i>ieses</i></p>
			<p><i>iera</i></p>
			<p><i>-</i></p>
		</Subjuntivo-Presente>
		<Subjuntivo-Pretérito-imperfecto-1>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>ieras</i></p>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>iéramos</i></p>
		</Subjuntivo-Pretérito-imperfecto-1>
		<Subjuntivo-Pretérito-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-perfecto>
		<Subjuntivo-Pretérito-pluscuamperfecto-1>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-pluscuamperfecto-1>
		<Subjuntivo-Futuro>
			<p><i>iré</i></p>
			<p><i>iría</i></p>
			<p><i>ieres</i></p>
			<p><i>irá</i></p>
			<p><i>iría</i></p>
			<p><i>iéremos</i></p>
		</Subjuntivo-Futuro>
		<Subjuntivo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Futuro-perfecto>
	</Subjuntivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>-</i></p>
			<p><i>-</i></p>
			<p><i>iendo</i></p>
			<p><i>-</i></p>
			<p><i>-</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-non>
			<p><i>ir</i></p>
			<p><i>-</i></p>
			<p><i>-</i></p>
			<p><i>ido</i></p>
			<p><i>-</i></p>
		</Imperativo-non>
	</Imperativo>
</template>

<template name="act:uar">
	<Indicativo>
		<Indicativo-Presente>
			<p><i>ía</i></p>
			<p><i>-</i></p>
			<p><i>iste</i></p>
			<p><i>ía</i></p>
			<p><i>imos</i></p>
		</Indicativo-Presente>
		<Indicativo-Pretérito-imperfecto>
			<p><i>-</i></p>
			<p><i>í</i></p>
			<p><i>ías</i></p>
			<p><i>-</i></p>
			<p><i>ió</i></p>
			<p><i>íamos</i></p>
		</Indicativo-Pretérito-imperfecto>
		<Indicativo-Pretérito-perfecto-compuesto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-perfecto-compuesto>
		<Indicativo-Pretérito-pluscuamperfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-pluscuamperfecto>
		<Indicativo-Futuro>
			<p><i>iere</i></p>
			<p><i>irás</i></p>
			<p><i>irías</i></p>
			<p><i>iere</i></p>
			<p><i>iremos</i></p>
		</Indicativo-Futuro>
		<Indicativo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Futuro-perfecto>
		<Indicativo-presente>
			<p><i>úo</i></p>
			<p><i>úas</i></p>
			<p><i>úa</i></p>
			<p><i>uamos</i></p>
			<p><i>uáis</i></p>
			<p><i>úan</i></p>
		</Indicativo-presente>
		<Indicativo-pretérito-perfecto-compuesto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-pretérito-perfecto-compuesto>
		<Indicativo-pretérito-imperfecto>
			<p><i>uaba</i></p>
			<p><i>uabas</i></p>
			<p><i>uaba</i></p>
			<p><i>uábamos</i></p>
			<p><i>uabais</i></p>
			<p><i>uaban</i></p>
		</Indicativo-pretérito-imperfecto>
		<Indicativo-pretérito-pluscuamperfecto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-pretérito-pluscuamperfecto>
		<Indicativo-pretérito-perfecto-simple>
			<p><i>ué</i></p>
			<p><i>uaste</i></p>
			<p><i>uó</i></p>
			<p><i>uamos</i></p>
			<p><i>uasteis</i></p>
			<p><i>uaron</i></p>
		</Indicativo-pretérito-perfecto-simple>
		<Indicativo-pretérito-anterior>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-pretérito-anterior>
		<Indicativo-futuro>
			<p><i>uaré</i></p>
			<p><i>uarás</i></p>
			<p><i>uará</i></p>
			<p><i>uaremos</i></p>
			<p><i>uaréis</i></p>
			<p><i>uarán</i></p>
		</Indicativo-futuro>
		<Indicativo-futuro-perfecto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Indicativo-futuro-perfecto>
	</Indicativo>
	<Subjuntivo>
		<Subjuntivo-Presente>
			<p><i>iera</i></p>
			<p><i>-</i></p>
			<p><i>ieses</i></p>
			<p><i>iera</i></p>
			<p><i>-</i></p>
		</Subjuntivo-Presente>
		<Subjuntivo-Pretérito-imperfecto-1>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>ieras</i></p>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>iéramos</i></p>
		</Subjuntivo-Pretérito-imperfecto-1>
		<Subjuntivo-Pretérito-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-perfecto>
		<Subjuntivo-Pretérito-pluscuamperfecto-1>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-pluscuamperfecto-1>
		<Subjuntivo-Futuro>
			<p><i>iré</i></p>
			<p><i>iría</i></p>
			<p><i>ieres</i></p>
			<p><i>irá</i></p>
			<p><i>iría</i></p>
			<p><i>iéremos</i></p>
		</Subjuntivo-Futuro>
		<Subjuntivo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Futuro-perfecto>
		<Subjuntivo-presente>
			<p><i>úe</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uéis</i></p>
			<p><i>úen</i></p>
		</Subjuntivo-presente>
		<Subjuntivo-pretérito-perfecto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Subjuntivo-pretérito-perfecto>
		<Subjuntivo-pretérito-imperfecto-1>
			<p><i>uara</i></p>
			<p><i>uaras</i></p>
			<p><i>uara</i></p>
			<p><i>uáramos</i></p>
			<p><i>uarais</i></p>
			<p><i>uaran</i></p>
		</Subjuntivo-pretérito-imperfecto-1>
		<Subjuntivo-pretérito-pluscuamperfecto-1>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Subjuntivo-pretérito-pluscuamperfecto-1>
		<Subjuntivo-pretérito-imperfecto-2>
			<p><i>uase</i></p>
			<p><i>uases</i></p>
			<p><i>uase</i></p>
			<p><i>uásemos</i></p>
			<p><i>uaseis</i></p>
			<p><i>uasen</i></p>
		</Subjuntivo-pretérito-imperfecto-2>
		<Subjuntivo-pretérito-pluscuamperfecto-2>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Subjuntivo-pretérito-pluscuamperfecto-2>
		<Subjuntivo-futuro>
			<p><i>uare</i></p>
			<p><i>uares</i></p>
			<p><i>uare</i></p>
			<p><i>uáremos</i></p>
			<p><i>uareis</i></p>
			<p><i>uaren</i></p>
		</Subjuntivo-futuro>
		<Subjuntivo-futuro-perfecto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Subjuntivo-futuro-perfecto>
	</Subjuntivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>úa</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uad</i></p>
			<p><i>úen</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-non>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uéis</i></p>
			<p><i>úen</i></p>
		</Imperativo-non>
	</Imperativo>
	<Condicional>
		<Condicional-Condicional>
			<p><i>uaría</i></p>
			<p><i>uarías</i></p>
			<p><i>uaría</i></p>
			<p><i>uaríamos</i></p>
			<p><i>uaríais</i></p>
			<p><i>uarían</i></p>
		</Condicional-Condicional>
		<Condicional-perfecto>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
			<p><i>uado</i></p>
		</Condicional-perfecto>
	</Condicional>
	<Infinitivo>
		<Infinitivo-Infinitivo>
			<p><i>uar</i></p>
			<p><i>uado</i></p>
		</Infinitivo-Infinitivo>
	</Infinitivo>
	<Gerundio>
		<Gerundio-Gerondio>
			<p><i>uando</i></p>
			<p><i>uado</i></p>
		</Gerundio-Gerondio>
	</Gerundio>
	<Participo>
		<Participo-Participo>
			<p><i>uado</i></p>
		</Participo-Participo>
	</Participo>
</template>

<template name="adqui:rir">
	<Indicativo>
		<Indicativo-Presente>
			<p><i>ía</i></p>
			<p><i>-</i></p>
			<p><i>iste</i></p>
			<p><i>ía</i></p>
			<p><i>imos</i></p>
		</Indicativo-Presente>
		<Indicativo-Pretérito-imperfecto>
			<p><i>-</i></p>
			<p><i>í</i></p>
			<p><i>ías</i></p>
			<p><i>-</i></p>
			<p><i>ió</i></p>
			<p><i>íamos</i></p>
		</Indicativo-Pretérito-imperfecto>
		<Indicativo-Pretérito-perfecto-compuesto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-perfecto-compuesto>
		<Indicativo-Pretérito-pluscuamperfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-pluscuamperfecto>
		<Indicativo-Futuro>
			<p><i>iere</i></p>
			<p><i>irás</i></p>
			<p><i>irías</i></p>
			<p><i>iere</i></p>
			<p><i>iremos</i></p>
		</Indicativo-Futuro>
		<Indicativo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Futuro-perfecto>
		<Indicativo-presente>
			<p><i>ero</i></p>
			<p><i>eres</i></p>
			<p><i>ere</i></p>
			<p><i>rimos</i></p>
			<p><i>rís</i></p>
			<p><i>eren</i></p>
		</Indicativo-presente>
		<Indicativo-pretérito-perfecto-compuesto>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Indicativo-pretérito-perfecto-compuesto>
		<Indicativo-pretérito-imperfecto>
			<p><i>ría</i></p>
			<p><i>rías</i></p>
			<p><i>ría</i></p>
			<p><i>ríamos</i></p>
			<p><i>ríais</i></p>
			<p><i>rían</i></p>
		</Indicativo-pretérito-imperfecto>
		<Indicativo-pretérito-pluscuamperfecto>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Indicativo-pretérito-pluscuamperfecto>
		<Indicativo-pretérito-perfecto-simple>
			<p><i>rí</i></p>
			<p><i>riste</i></p>
			<p><i>rió</i></p>
			<p><i>rimos</i></p>
			<p><i>risteis</i></p>
			<p><i>rieron</i></p>
		</Indicativo-pretérito-perfecto-simple>
		<Indicativo-pretérito-anterior>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Indicativo-pretérito-anterior>
		<Indicativo-futuro>
			<p><i>riré</i></p>
			<p><i>rirás</i></p>
			<p><i>rirá</i></p>
			<p><i>riremos</i></p>
			<p><i>riréis</i></p>
			<p><i>rirán</i></p>
		</Indicativo-futuro>
		<Indicativo-futuro-perfecto>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Indicativo-futuro-perfecto>
	</Indicativo>
	<Subjuntivo>
		<Subjuntivo-Presente>
			<p><i>iera</i></p>
			<p><i>-</i></p>
			<p><i>ieses</i></p>
			<p><i>iera</i></p>
			<p><i>-</i></p>
		</Subjuntivo-Presente>
		<Subjuntivo-Pretérito-imperfecto-1>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>ieras</i></p>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>iéramos</i></p>
		</Subjuntivo-Pretérito-imperfecto-1>
		<Subjuntivo-Pretérito-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-perfecto>
		<Subjuntivo-Pretérito-pluscuamperfecto-1>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-pluscuamperfecto-1>
		<Subjuntivo-Futuro>
			<p><i>iré</i></p>
			<p><i>iría</i></p>
			<p><i>ieres</i></p>
			<p><i>irá</i></p>
			<p><i>iría</i></p>
			<p><i>iéremos</i></p>
		</Subjuntivo-Futuro>
		<Subjuntivo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Futuro-perfecto>
		<Subjuntivo-presente>
			<p><i>era</i></p>
			<p><i>eras</i></p>
			<p><i>era</i></p>
			<p><i>ramos</i></p>
			<p><i>ráis</i></p>
			<p><i>eran</i></p>
		</Subjuntivo-presente>
		<Subjuntivo-pretérito-perfecto>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Subjuntivo-pretérito-perfecto>
		<Subjuntivo-pretérito-imperfecto-1>
			<p><i>riera</i></p>
			<p><i>rieras</i></p>
			<p><i>riera</i></p>
			<p><i>riéramos</i></p>
			<p><i>rierais</i></p>
			<p><i>rieran</i></p>
		</Subjuntivo-pretérito-imperfecto-1>
		<Subjuntivo-pretérito-pluscuamperfecto-1>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Subjuntivo-pretérito-pluscuamperfecto-1>
		<Subjuntivo-pretérito-imperfecto-2>
			<p><i>riese</i></p>
			<p><i>rieses</i></p>
			<p><i>riese</i></p>
			<p><i>riésemos</i></p>
			<p><i>rieseis</i></p>
			<p><i>riesen</i></p>
		</Subjuntivo-pretérito-imperfecto-2>
		<Subjuntivo-pretérito-pluscuamperfecto-2>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Subjuntivo-pretérito-pluscuamperfecto-2>
		<Subjuntivo-futuro>
			<p><i>riere</i></p>
			<p><i>rieres</i></p>
			<p><i>riere</i></p>
			<p><i>riéremos</i></p>
			<p><i>riereis</i></p>
			<p><i>rieren</i></p>
		</Subjuntivo-futuro>
		<Subjuntivo-futuro-perfecto>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Subjuntivo-futuro-perfecto>
	</Subjuntivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>ere</i></p>
			<p><i>era</i></p>
			<p><i>ramos</i></p>
			<p><i>rid</i></p>
			<p><i>eran</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-non>
			<p><i>eras</i></p>
			<p><i>era</i></p>
			<p><i>ramos</i></p>
			<p><i>ráis</i></p>
			<p><i>eran</i></p>
		</Imperativo-non>
	</Imperativo>
	<Condicional>
		<Condicional-Condicional>
			<p><i>riría</i></p>
			<p><i>rirías</i></p>
			<p><i>riría</i></p>
			<p><i>riríamos</i></p>
			<p><i>riríais</i></p>
			<p><i>rirían</i></p>
		</Condicional-Condicional>
		<Condicional-perfecto>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
			<p><i>rido</i></p>
		</Condicional-perfecto>
	</Condicional>
	<Infinitivo>
		<Infinitivo-Infinitivo>
			<p><i>rir</i></p>
			<p><i>rido</i></p>
		</Infinitivo-Infinitivo>
	</Infinitivo>
	<Gerundio>
		<Gerundio-Gerondio>
			<p><i>riendo</i></p>
			<p><i>rido</i></p>
		</Gerundio-Gerondio>
	</Gerundio>
	<Participo>
		<Participo-Participo>
			<p><i>rido</i></p>
		</Participo-Participo>
	</Participo>
</template>

<template name="ah:incar">
	<Indicativo>
		<Indicativo-Presente>
			<p><i>ía</i></p>
			<p><i>-</i></p>
			<p><i>iste</i></p>
			<p><i>ía</i></p>
			<p><i>imos</i></p>
		</Indicativo-Presente>
		<Indicativo-Pretérito-imperfecto>
			<p><i>-</i></p>
			<p><i>í</i></p>
			<p><i>ías</i></p>
			<p><i>-</i></p>
			<p><i>ió</i></p>
			<p><i>íamos</i></p>
		</Indicativo-Pretérito-imperfecto>
		<Indicativo-Pretérito-perfecto-compuesto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-perfecto-compuesto>
		<Indicativo-Pretérito-pluscuamperfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Pretérito-pluscuamperfecto>
		<Indicativo-Futuro>
			<p><i>iere</i></p>
			<p><i>irás</i></p>
			<p><i>irías</i></p>
			<p><i>iere</i></p>
			<p><i>iremos</i></p>
		</Indicativo-Futuro>
		<Indicativo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Indicativo-Futuro-perfecto>
		<Indicativo-presente>
			<p><i>ínco</i></p>
			<p><i>íncas</i></p>
			<p><i>ínca</i></p>
			<p><i>incamos</i></p>
			<p><i>incáis</i></p>
			<p><i>íncan</i></p>
		</Indicativo-presente>
		<Indicativo-pretérito-perfecto-compuesto>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Indicativo-pretérito-perfecto-compuesto>
		<Indicativo-pretérito-imperfecto>
			<p><i>incaba</i></p>
			<p><i>incabas</i></p>
			<p><i>incaba</i></p>
			<p><i>incábamos</i></p>
			<p><i>incabais</i></p>
			<p><i>incaban</i></p>
		</Indicativo-pretérito-imperfecto>
		<Indicativo-pretérito-pluscuamperfecto>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Indicativo-pretérito-pluscuamperfecto>
		<Indicativo-pretérito-perfecto-simple>
			<p><i>inqué</i></p>
			<p><i>incaste</i></p>
			<p><i>incó</i></p>
			<p><i>incamos</i></p>
			<p><i>incasteis</i></p>
			<p><i>incaron</i></p>
		</Indicativo-pretérito-perfecto-simple>
		<Indicativo-pretérito-anterior>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Indicativo-pretérito-anterior>
		<Indicativo-futuro>
			<p><i>incaré</i></p>
			<p><i>incarás</i></p>
			<p><i>incará</i></p>
			<p><i>incaremos</i></p>
			<p><i>incaréis</i></p>
			<p><i>incarán</i></p>
		</Indicativo-futuro>
		<Indicativo-futuro-perfecto>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Indicativo-futuro-perfecto>
	</Indicativo>
	<Subjuntivo>
		<Subjuntivo-Presente>
			<p><i>iera</i></p>
			<p><i>-</i></p>
			<p><i>ieses</i></p>
			<p><i>iera</i></p>
			<p><i>-</i></p>
		</Subjuntivo-Presente>
		<Subjuntivo-Pretérito-imperfecto-1>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>ieras</i></p>
			<p><i>-</i></p>
			<p><i>iese</i></p>
			<p><i>iéramos</i></p>
		</Subjuntivo-Pretérito-imperfecto-1>
		<Subjuntivo-Pretérito-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-perfecto>
		<Subjuntivo-Pretérito-pluscuamperfecto-1>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Pretérito-pluscuamperfecto-1>
		<Subjuntivo-Futuro>
			<p><i>iré</i></p>
			<p><i>iría</i></p>
			<p><i>ieres</i></p>
			<p><i>irá</i></p>
			<p><i>iría</i></p>
			<p><i>iéremos</i></p>
		</Subjuntivo-Futuro>
		<Subjuntivo-Futuro-perfecto>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
			<p><i>ido</i></p>
		</Subjuntivo-Futuro-perfecto>
		<Subjuntivo-presente>
			<p><i>ínque</i></p>
			<p><i>ínques</i></p>
			<p><i>ínque</i></p>
			<p><i>inquemos</i></p>
			<p><i>inquéis</i></p>
			<p><i>ínquen</i></p>
		</Subjuntivo-presente>
		<Subjuntivo-pretérito-perfecto>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Subjuntivo-pretérito-perfecto>
		<Subjuntivo-pretérito-imperfecto-1>
			<p><i>incara</i></p>
			<p><i>incaras</i></p>
			<p><i>incara</i></p>
			<p><i>incáramos</i></p>
			<p><i>incarais</i></p>
			<p><i>incaran</i></p>
		</Subjuntivo-pretérito-imperfecto-1>
		<Subjuntivo-pretérito-pluscuamperfecto-1>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Subjuntivo-pretérito-pluscuamperfecto-1>
		<Subjuntivo-pretérito-imperfecto-2>
			<p><i>incase</i></p>
			<p><i>incases</i></p>
			<p><i>incase</i></p>
			<p><i>incásemos</i></p>
			<p><i>incaseis</i></p>
			<p><i>incasen</i></p>
		</Subjuntivo-pretérito-imperfecto-2>
		<Subjuntivo-pretérito-pluscuamperfecto-2>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Subjuntivo-pretérito-pluscuamperfecto-2>
		<Subjuntivo-futuro>
			<p><i>incare</i></p>
			<p><i>incares</i></p>
			<p><i>incare</i></p>
			<p><i>incáremos</i></p>
			<p><i>incareis</i></p>
			<p><i>incaren</i></p>
		</Subjuntivo-futuro>
		<Subjuntivo-futuro-perfecto>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
			<p><i>incado</i></p>
		</Subjuntivo-futuro-perfecto>
	</Subjuntivo>
	<Imperativo>
		<Imperativo-Afirmativo>
			<p><i>ínca</i></p>
			<p><i>ínque</i></p>
			<p><i>inquemos</i></p>
			<p><i>incad</i></p>
			<p><i>ínquen</i></p>
		</Imperativo-Afirmativo>
		<Imperativo-non>
			<p><i>ínques</i></p>
			<p><i>ínque</i></p>
			<p><i>inquemos</i></p>
			<p><i>inquéis</i></p>
			<p><i>ínquen</i></p>
		</Imperativo-non>
	</Imperativo>
	<Condicional>
		<Condicional-Condicional>
			<p><i>incaría</i></p>