<?xml version="1.0" encoding='utf-8'?>

<!--
	verbs-en.xml - List of English verbs with their conjugation template.
	The templates were generated by SekouDiaoNlp using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.

	Copyright (C) 2018 SekouDiaoNlp <https://github.com/SekouDiaoNlp>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE verbs-en [
    <!ELEMENT verbs-en (v)+>
    <!ATTLIST verbs-en
      xmlns CDATA #FIXED ''>

    <!ELEMENT v (i,t)> <!-- verb's conjugation information (infinitive, radical) -->
    <!ATTLIST v
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>  <!-- infinitive -->
    <!ATTLIST i
      xmlns CDATA #FIXED ''>

    <!ELEMENT t (#PCDATA)> <!-- template (radical:termination) -->
    <!ATTLIST t
        xmlns CDATA #FIXED ''>
]>

<verbs-en>

<v><i>Americanise</i>		<t>lov:e</t></v>
<v><i>Americanize</i>		<t>lov:e</t></v>
<v><i>Frenchify</i>		<t>:Frenchify</t></v>
<v><i>KO</i>		<t>KO:</t></v>
<v><i>X-rate</i>		<t>lov:e</t></v>
<v><i>X-ray</i>		<t>turn:</t></v>
<v><i>abandon</i>		<t>turn:</t></v>
<v><i>abase</i>		<t>lov:e</t></v>
<v><i>abate</i>		<t>lov:e</t></v>
<v><i>abbreviate</i>		<t>lov:e</t></v>
<v><i>abdicate</i>		<t>lov:e</t></v>
<v><i>abduct</i>		<t>turn:</t></v>
<v><i>abet</i>		<t>permit:</t></v>
<v><i>abhor</i>		<t>star:</t></v>
<v><i>abide</i>		<t>abid:e</t></v>
<v><i>abjure</i>		<t>lov:e</t></v>
<v><i>abolish</i>		<t>touch:</t></v>
<v><i>abominate</i>		<t>lov:e</t></v>
<v><i>abort</i>		<t>turn:</t></v>
<v><i>abound</i>		<t>turn:</t></v>
<v><i>abrade</i>		<t>lov:e</t></v>
<v><i>abridge</i>		<t>lov:e</t></v>
<v><i>abrogate</i>		<t>lov:e</t></v>
<v><i>abseil</i>		<t>turn:</t></v>
<v><i>absent</i>		<t>turn:</t></v>
<v><i>absolve</i>		<t>lov:e</t></v>
<v><i>absorb</i>		<t>turn:</t></v>
<v><i>abstain</i>		<t>turn:</t></v>
<v><i>abstract</i>		<t>turn:</t></v>
<v><i>abuse</i>		<t>lov:e</t></v>
<v><i>abut</i>		<t>permit:</t></v>
<v><i>accede</i>		<t>lov:e</t></v>
<v><i>accelerate</i>		<t>lov:e</t></v>
<v><i>accent</i>		<t>turn:</t></v>
<v><i>accentuate</i>		<t>lov:e</t></v>
<v><i>accept</i>		<t>turn:</t></v>
<v><i>acclaim</i>		<t>turn:</t></v>
<v><i>acclimatise</i>		<t>lov:e</t></v>
<v><i>acclimatize</i>		<t>lov:e</t></v>
<v><i>accommodate</i>		<t>lov:e</t></v>
<v><i>accompany</i>		<t>carr:y</t></v>
<v><i>accomplish</i>		<t>touch:</t></v>
<v><i>accord</i>		<t>turn:</t></v>
<v><i>accost</i>		<t>turn:</t></v>
<v><i>account</i>		<t>turn:</t></v>
<v><i>accredit</i>		<t>turn:</t></v>
<v><i>accrue</i>		<t>lov:e</t></v>
<v><i>accumulate</i>		<t>lov:e</t></v>
<v><i>accuse</i>		<t>lov:e</t></v>
<v><i>accustom</i>		<t>turn:</t></v>
<v><i>ache</i>		<t>lov:e</t></v>
<v><i>achieve</i>		<t>lov:e</t></v>
<v><i>acidify</i>		<t>carr:y</t></v>
<v><i>acknowledge</i>		<t>lov:e</t></v>
<v><i>acquiesce</i>		<t>lov:e</t></v>
<v><i>acquire</i>		<t>lov:e</t></v>
<v><i>acquit</i>		<t>permit:</t></v>
<v><i>act</i>		<t>turn:</t></v>
<v><i>activate</i>		<t>lov:e</t></v>
<v><i>actuate</i>		<t>lov:e</t></v>
<v><i>ad-lib</i>		<t>turn:</t></v>
<v><i>adapt</i>		<t>turn:</t></v>
<v><i>add</i>		<t>turn:</t></v>
<v><i>addle</i>		<t>lov:e</t></v>
<v><i>address</i>		<t>touch:</t></v>
<v><i>adhere</i>		<t>lov:e</t></v>
<v><i>adjoin</i>		<t>turn:</t></v>
<v><i>adjourn</i>		<t>turn:</t></v>
<v><i>adjudge</i>		<t>lov:e</t></v>
<v><i>adjure</i>		<t>lov:e</t></v>
<v><i>adjust</i>		<t>turn:</t></v>
<v><i>administer</i>		<t>turn:</t></v>
<v><i>administrate</i>		<t>lov:e</t></v>
<v><i>admire</i>		<t>lov:e</t></v>
<v><i>admit</i>		<t>permit:</t></v>
<v><i>admonish</i>		<t>touch:</t></v>
<v><i>adopt</i>		<t>turn:</t></v>
<v><i>adore</i>		<t>lov:e</t></v>
<v><i>adorn</i>		<t>turn:</t></v>
<v><i>adulate</i>		<t>lov:e</t></v>
<v><i>adulterate</i>		<t>lov:e</t></v>
<v><i>advance</i>		<t>lov:e</t></v>
<v><i>advantage</i>		<t>lov:e</t></v>
<v><i>adventure</i>		<t>lov:e</t></v>
<v><i>advert</i>		<t>turn:</t></v>
<v><i>advertise</i>		<t>lov:e</t></v>
<v><i>advise</i>		<t>lov:e</t></v>
<v><i>advocate</i>		<t>lov:e</t></v>
<v><i>aerate</i>		<t>lov:e</t></v>
<v><i>aestheticise</i>		<t>lov:e</t></v>
<v><i>aestheticize</i>		<t>lov:e</t></v>
<v><i>affect</i>		<t>turn:</t></v>
<v><i>affiliate to/with</i>		<t>lov:e</t></v>
<v><i>affirm</i>		<t>turn:</t></v>
<v><i>affix</i>		<t>touch:</t></v>
<v><i>afflict</i>		<t>turn:</t></v>
<v><i>afford</i>		<t>turn:</t></v>
<v><i>afforest</i>		<t>turn:</t></v>
<v><i>affront</i>		<t>turn:</t></v>
<v><i>age</i>		<t>lov:e</t></v>
<v><i>agglomerate</i>		<t>lov:e</t></v>
<v><i>agglutinate</i>		<t>lov:e</t></v>
<v><i>aggravate</i>		<t>lov:e</t></v>
<v><i>aggregate</i>		<t>lov:e</t></v>
<v><i>agitate</i>		<t>lov:e</t></v>
<v><i>agonise</i>		<t>lov:e</t></v>
<v><i>agonize</i>		<t>lov:e</t></v>
<v><i>agree</i>		<t>hear:</t></v>
<v><i>aid</i>		<t>turn:</t></v>
<v><i>ail</i>		<t>turn:</t></v>
<v><i>aim</i>		<t>turn:</t></v>
<v><i>air</i>		<t>turn:</t></v>
<v><i>air-condition</i>		<t>turn:</t></v>
<v><i>airmail</i>		<t>turn:</t></v>
<v><i>alarm</i>		<t>turn:</t></v>
<v><i>alcoholise</i>		<t>lov:e</t></v>
<v><i>alcoholize</i>		<t>lov:e</t></v>
<v><i>alert</i>		<t>turn:</t></v>
<v><i>alienate</i>		<t>lov:e</t></v>
<v><i>alight</i>		<t>turn:</t></v>
<v><i>align</i>		<t>turn:</t></v>
<v><i>alkalify</i>		<t>carr:y</t></v>
<v><i>allay</i>		<t>turn:</t></v>
<v><i>allege</i>		<t>lov:e</t></v>
<v><i>alleviate</i>		<t>lov:e</t></v>
<v><i>alliterate</i>		<t>lov:e</t></v>
<v><i>allocate</i>		<t>lov:e</t></v>
<v><i>allot</i>		<t>permit:</t></v>
<v><i>allow</i>		<t>turn:</t></v>
<v><i>allude to</i>		<t>lov:e</t></v>
<v><i>allure</i>		<t>lov:e</t></v>
<v><i>ally</i>		<t>carr:y</t></v>
<v><i>alphabetise</i>		<t>lov:e</t></v>
<v><i>alphabetize</i>		<t>lov:e</t></v>
<v><i>alter</i>		<t>turn:</t></v>
<v><i>alternate</i>		<t>lov:e</t></v>
<v><i>amalgamate</i>		<t>lov:e</t></v>
<v><i>amass</i>		<t>turn:</t></v>
<v><i>amaze</i>		<t>lov:e</t></v>
<v><i>amble</i>		<t>lov:e</t></v>
<v><i>ambush</i>		<t>touch:</t></v>
<v><i>ameliorate</i>		<t>lov:e</t></v>
<v><i>amend</i>		<t>turn:</t></v>
<v><i>amortise</i>		<t>lov:e</t></v>
<v><i>amortize</i>		<t>lov:e</t></v>
<v><i>amount</i>		<t>turn:</t></v>
<v><i>amplify</i>		<t>carr:y</t></v>
<v><i>amputate</i>		<t>lov:e</t></v>
<v><i>amuse</i>		<t>lov:e</t></v>
<v><i>anaesthetise</i>		<t>lov:e</t></v>
<v><i>anaesthetize</i>		<t>lov:e</t></v>
<v><i>analyse</i>		<t>lov:e</t></v>
<v><i>anathematise</i>		<t>lov:e</t></v>
<v><i>anathematize</i>		<t>lov:e</t></v>
<v><i>anatomise</i>		<t>lov:e</t></v>
<v><i>anatomize</i>		<t>lov:e</t></v>
<v><i>anchor</i>		<t>turn:</t></v>
<v><i>anesthetise</i>		<t>lov:e</t></v>
<v><i>anesthetize</i>		<t>lov:e</t></v>
<v><i>anger</i>		<t>turn:</t></v>
<v><i>angle</i>		<t>lov:e</t></v>
<v><i>anglicise</i>		<t>lov:e</t></v>
<v><i>anglicize</i>		<t>lov:e</t></v>
<v><i>animate</i>		<t>lov:e</t></v>
<v><i>annex</i>		<t>touch:</t></v>
<v><i>annihilate</i>		<t>lov:e</t></v>
<v><i>annotate</i>		<t>lov:e</t></v>
<v><i>announce</i>		<t>lov:e</t></v>
<v><i>annoy</i>		<t>turn:</t></v>
<v><i>annul</i>		<t>model:</t></v>
<v><i>anoint</i>		<t>turn:</t></v>
<v><i>answer</i>		<t>turn:</t></v>
<v><i>antagonise</i>		<t>lov:e</t></v>
<v><i>antagonize</i>		<t>lov:e</t></v>
<v><i>antedate</i>		<t>lov:e</t></v>
<v><i>anticipate</i>		<t>lov:e</t></v>
<v><i>ape</i>		<t>lov:e</t></v>
<v><i>apologise (BE) for</i>		<t>lov:e</t></v>
<v><i>apologize (AE, BE) for</i>		<t>lov:e</t></v>
<v><i>appal (BE, AE)</i>		<t>model:</t></v>
<v><i>appall (AE)</i>		<t>turn:</t></v>
<v><i>appeal</i>		<t>turn:</t></v>
<v><i>appear</i>		<t>turn:</t></v>
<v><i>appease</i>		<t>lov:e</t></v>
<v><i>append</i>		<t>turn:</t></v>
<v><i>appertain to</i>		<t>turn:</t></v>
<v><i>applaud</i>		<t>turn:</t></v>
<v><i>apply</i>		<t>carr:y</t></v>
<v><i>appoint ( to)</i>		<t>turn:</t></v>
<v><i>apportion</i>		<t>turn:</t></v>
<v><i>appraise</i>		<t>lov:e</t></v>
<v><i>appreciate</i>		<t>lov:e</t></v>
<v><i>apprehend</i>		<t>turn:</t></v>
<v><i>apprentice</i>		<t>lov:e</t></v>
<v><i>apprise of</i>		<t>lov:e</t></v>
<v><i>approach</i>		<t>touch:</t></v>
<v><i>approbate</i>		<t>lov:e</t></v>
<v><i>appropriate</i>		<t>lov:e</t></v>
<v><i>approve</i>		<t>lov:e</t></v>
<v><i>approximate to</i>		<t>lov:e</t></v>
<v><i>arbitrate</i>		<t>lov:e</t></v>
<v><i>arc</i>		<t>turn:</t></v>
<v><i>arch</i>		<t>touch:</t></v>
<v><i>argue</i>		<t>lov:e</t></v>
<v><i>arise</i>		<t>ar:ise</t></v>
<v><i>arm</i>		<t>turn:</t></v>
<v><i>armour</i>		<t>turn:</t></v>
<v><i>arouse</i>		<t>lov:e</t></v>
<v><i>arraign</i>		<t>turn:</t></v>
<v><i>arrange</i>		<t>lov:e</t></v>
<v><i>array</i>		<t>turn:</t></v>
<v><i>arrest</i>		<t>turn:</t></v>
<v><i>arrive</i>		<t>lov:e</t></v>
<v><i>arrogate</i>		<t>lov:e</t></v>
<v><i>articulate</i>		<t>lov:e</t></v>
<v><i>ascertain</i>		<t>turn:</t></v>
<v><i>ascribe</i>		<t>lov:e</t></v>
<v><i>ask</i>		<t>turn:</t></v>
<v><i>aspirate</i>		<t>lov:e</t></v>
<v><i>aspire to</i>		<t>lov:e</t></v>
<v><i>assail</i>		<t>turn:</t></v>
<v><i>assassinate</i>		<t>lov:e</t></v>
<v><i>assault</i>		<t>turn:</t></v>
<v><i>assemble</i>		<t>lov:e</t></v>
<v><i>assent</i>		<t>turn:</t></v>
<v><i>assert</i>		<t>turn:</t></v>
<v><i>assess</i>		<t>touch:</t></v>
<v><i>assign</i>		<t>turn:</t></v>
<v><i>assimilate</i>		<t>lov:e</t></v>
<v><i>assist</i>		<t>turn:</t></v>
<v><i>associate</i>		<t>lov:e</t></v>
<v><i>assort</i>		<t>turn:</t></v>
<v><i>assume</i>		<t>lov:e</t></v>
<v><i>assure</i>		<t>lov:e</t></v>
<v><i>astonish</i>		<t>touch:</t></v>
<v><i>astound</i>		<t>turn:</t></v>
<v><i>atomise</i>		<t>lov:e</t></v>
<v><i>atomize</i>		<t>lov:e</t></v>
<v><i>atone for</i>		<t>lov:e</t></v>
<v><i>atrophy</i>		<t>carr:y</t></v>
<v><i>attach</i>		<t>touch:</t></v>
<v><i>attack</i>		<t>turn:</t></v>
<v><i>attain</i>		<t>turn:</t></v>
<v><i>attempt</i>		<t>turn:</t></v>
<v><i>attend</i>		<t>turn:</t></v>
<v><i>attenuate</i>		<t>lov:e</t></v>
<v><i>attest</i>		<t>turn:</t></v>
<v><i>attire in/with</i>		<t>lov:e</t></v>
<v><i>attract</i>		<t>turn:</t></v>
<v><i>attribute</i>		<t>lov:e</t></v>
<v><i>attune</i>		<t>lov:e</t></v>
<v><i>audit</i>		<t>turn:</t></v>
<v><i>audition</i>		<t>turn:</t></v>
<v><i>augment</i>		<t>turn:</t></v>
<v><i>augur</i>		<t>turn:</t></v>
<v><i>auscultate</i>		<t>lov:e</t></v>
<v><i>authenticate</i>		<t>lov:e</t></v>
<v><i>author</i>		<t>turn:</t></v>
<v><i>authorise</i>		<t>lov:e</t></v>
<v><i>authorize</i>		<t>lov:e</t></v>
<v><i>autograph</i>		<t>turn:</t></v>
<v><i>automate</i>		<t>lov:e</t></v>
<v><i>automatise</i>		<t>lov:e</t></v>
<v><i>automatize</i>		<t>lov:e</t></v>
<v><i>avail oneself of</i>		<t>:avail oneself of</t></v>
<v><i>avalanche</i>		<t>lov:e</t></v>
<v><i>avenge</i>		<t>lov:e</t></v>
<v><i>average</i>		<t>lov:e</t></v>
<v><i>avert</i>		<t>turn:</t></v>
<v><i>avoid</i>		<t>turn:</t></v>
<v><i>await</i>		<t>turn:</t></v>
<v><i>awake</i>		<t>aw:ake</t></v>
<v><i>awaken</i>		<t>turn:</t></v>
<v><i>award</i>		<t>turn:</t></v>
<v><i>awe</i>		<t>lov:e</t></v>
<v><i>ax</i>		<t>touch:</t></v>
<v><i>axe</i>		<t>lov:e</t></v>
<v><i>baa</i>		<t>turn:</t></v>
<v><i>babble</i>		<t>lov:e</t></v>
<v><i>baby</i>		<t>touch:</t></v>
<v><i>baby-sit</i>		<t>s:it</t></v>
<v><i>back</i>		<t>turn:</t></v>
<v><i>backdate</i>		<t>lov:e</t></v>
<v><i>backfire</i>		<t>lov:e</t></v>
<v><i>backpack</i>		<t>turn:</t></v>
<v><i>backspace</i>		<t>lov:e</t></v>
<v><i>backtrack</i>		<t>turn:</t></v>
<v><i>badger</i>		<t>turn:</t></v>
<v><i>baffle</i>		<t>lov:e</t></v>
<v><i>bag</i>		<t>beg:</t></v>
<v><i>bail</i>		<t>turn:</t></v>
<v><i>bait</i>		<t>turn:</t></v>
<v><i>bake</i>		<t>lov:e</t></v>
<v><i>balance</i>		<t>lov:e</t></v>
<v><i>bale</i>		<t>lov:e</t></v>
<v><i>balk</i>		<t>turn:</t></v>
<v><i>balloon</i>		<t>turn:</t></v>
<v><i>ballot</i>		<t>turn:</t></v>
<v><i>ban</i>		<t>pin:</t></v>
<v><i>band</i>		<t>turn:</t></v>
<v><i>bandage</i>		<t>lov:e</t></v>
<v><i>bang</i>		<t>turn:</t></v>
<v><i>banish</i>		<t>touch:</t></v>
<v><i>bank</i>		<t>turn:</t></v>
<v><i>bankrupt</i>		<t>turn:</t></v>
<v><i>banter</i>		<t>turn:</t></v>
<v><i>baptise</i>		<t>lov:e</t></v>
<v><i>baptize</i>		<t>lov:e</t></v>
<v><i>bar</i>		<t>star:</t></v>
<v><i>barbecue</i>		<t>lov:e</t></v>
<v><i>bard</i>		<t>turn:</t></v>
<v><i>bare</i>		<t>lov:e</t></v>
<v><i>bargain</i>		<t>turn:</t></v>
<v><i>barge in</i>		<t>lov:e</t></v>
<v><i>bark</i>		<t>turn:</t></v>
<v><i>barricade</i>		<t>lov:e</t></v>
<v><i>barter</i>		<t>turn:</t></v>
<v><i>base</i>		<t>lov:e</t></v>
<v><i>bash</i>		<t>touch:</t></v>
<v><i>bask</i>		<t>turn:</t></v>
<v><i>bat</i>		<t>permit:</t></v>
<v><i>batch</i>		<t>touch:</t></v>
<v><i>bath</i>		<t>turn:</t></v>
<v><i>bathe</i>		<t>lov:e</t></v>
<v><i>batter</i>		<t>turn:</t></v>
<v><i>battle</i>		<t>lov:e</t></v>
<v><i>baulk</i>		<t>turn:</t></v>
<v><i>bawl</i>		<t>turn:</t></v>
<v><i>bay</i>		<t>turn:</t></v>
<v><i>be</i>		<t>:be</t></v>
<v><i>beach</i>		<t>touch:</t></v>
<v><i>bead</i>		<t>turn:</t></v>
<v><i>beam</i>		<t>turn:</t></v>
<v><i>bear</i>		<t>b:ear</t></v>
<v><i>beat</i>		<t>beat:</t></v>
<v><i>beatify</i>		<t>carr:y</t></v>
<v><i>beautify</i>		<t>carr:y</t></v>
<v><i>beckon</i>		<t>turn:</t></v>
<v><i>become</i>		<t>c:ome</t></v>
<v><i>bed</i>		<t>shred:</t></v>
<v><i>bedeck</i>		<t>turn:</t></v>
<v><i>bedevil</i>		<t>model:</t></v>
<v><i>beef</i>		<t>turn:</t></v>
<v><i>beep</i>		<t>turn:</t></v>
<v><i>beetle</i>		<t>lov:e</t></v>
<v><i>befall</i>		<t>f:all</t></v>
<v><i>befit</i>		<t>permit:</t></v>
<v><i>befriend</i>		<t>turn:</t></v>
<v><i>befuddle</i>		<t>lov:e</t></v>
<v><i>beg</i>		<t>beg:</t></v>
<v><i>beget</i>		<t>beg:et</t></v>
<v><i>begin</i>		<t>beg:in</t></v>
<v><i>beguile</i>		<t>lov:e</t></v>
<v><i>behave</i>		<t>lov:e</t></v>
<v><i>behead</i>		<t>turn:</t></v>
<v><i>behold</i>		<t>h:old</t></v>
<v><i>belch</i>		<t>turn:</t></v>
<v><i>belie</i>		<t>d:ie</t></v>
<v><i>believe</i>		<t>lov:e</t></v>
<v><i>belittle</i>		<t>lov:e</t></v>
<v><i>bellow</i>		<t>turn:</t></v>
<v><i>belong</i>		<t>turn:</t></v>
<v><i>belt</i>		<t>turn:</t></v>
<v><i>bemuse</i>		<t>lov:e</t></v>
<v><i>bend</i>		<t>ben:d</t></v>
<v><i>benefit</i>		<t>turn:</t></v>
<v><i>benumb</i>		<t>turn:</t></v>
<v><i>bequeath</i>		<t>turn:</t></v>
<v><i>berate</i>		<t>lov:e</t></v>
<v><i>bereave</i>		<t>bere:ave</t></v>
<v><i>berth</i>		<t>turn:</t></v>
<v><i>beseech</i>		<t>bes:eech</t></v>
<v><i>beset</i>		<t>set:</t></v>
<v><i>besiege ( with)</i>		<t>lov:e</t></v>
<v><i>besmirch</i>		<t>touch:</t></v>
<v><i>bespeak</i>		<t>besp:eak</t></v>
<v><i>best ( at)</i>		<t>turn:</t></v>
<v><i>bestow</i>		<t>turn:</t></v>
<v><i>bestrew</i>		<t>bestrew:</t></v>
<v><i>bestride</i>		<t>bestr:ide</t></v>
<v><i>bet</i>		<t>bet:</t></v>
<v><i>betray</i>		<t>turn:</t></v>
<v><i>betroth</i>		<t>turn:</t></v>
<v><i>better</i>		<t>turn:</t></v>
<v><i>beware (of)</i>		<t>lov:e</t></v>
<v><i>bewilder</i>		<t>turn:</t></v>
<v><i>bewitch</i>		<t>touch:</t></v>
<v><i>bicker</i>		<t>turn:</t></v>
<v><i>bicycle</i>		<t>lov:e</t></v>
<v><i>bid</i>		<t>bid:</t></v>
<v><i>bifurcate</i>		<t>lov:e</t></v>
<v><i>bike</i>		<t>lov:e</t></v>
<v><i>bilk</i>		<t>turn:</t></v>
<v><i>bill</i>		<t>turn:</t></v>
<v><i>billet</i>		<t>turn:</t></v>
<v><i>billow</i>		<t>turn:</t></v>
<v><i>bind</i>		<t>f:ind</t></v>
<v><i>bisect</i>		<t>turn:</t></v>
<v><i>bitch</i>		<t>touch:</t></v>
<v><i>bite</i>		<t>bit:e</t></v>
<v><i>bivouac</i>		<t>turn:</t></v>
<v><i>blab</i>		<t>mob:</t></v>
<v><i>black</i>		<t>turn:</t></v>
<v><i>blacken</i>		<t>turn:</t></v>
<v><i>blacklist</i>		<t>turn:</t></v>
<v><i>blackmail</i>		<t>turn:</t></v>
<v><i>blame</i>		<t>lov:e</t></v>
<v><i>blanch</i>		<t>touch:</t></v>
<v><i>blanket</i>		<t>turn:</t></v>
<v><i>blare</i>		<t>lov:e</t></v>
<v><i>blaspheme</i>		<t>lov:e</t></v>
<v><i>blast</i>		<t>turn:</t></v>
<v><i>blather</i>		<t>turn:</t></v>
<v><i>blaze</i>		<t>lov:e</t></v>
<v><i>blazon</i>		<t>turn:</t></v>
<v><i>bleach</i>		<t>touch:</t></v>
<v><i>bleat</i>		<t>turn:</t></v>
<v><i>bleed</i>		<t>ble:ed</t></v>
<v><i>bleep</i>		<t>turn:</t></v>
<v><i>blemish</i>		<t>touch:</t></v>
<v><i>blend</i>		<t>blen:d</t></v>
<v><i>bless</i>		<t>touch:</t></v>
<v><i>blight</i>		<t>turn:</t></v>
<v><i>blind</i>		<t>turn:</t></v>
<v><i>blindfold</i>		<t>turn:</t></v>
<v><i>blink</i>		<t>turn:</t></v>
<v><i>blister</i>		<t>turn:</t></v>
<v><i>blitz</i>		<t>touch:</t></v>
<v><i>block</i>		<t>turn:</t></v>
<v><i>blockade</i>		<t>lov:e</t></v>
<v><i>bloom</i>		<t>turn:</t></v>
<v><i>blossom</i>		<t>turn:</t></v>
<v><i>blot</i>		<t>permit:</t></v>
<v><i>blow</i>		<t>kn:ow</t></v>
<v><i>bludgeon</i>		<t>turn:</t></v>
<v><i>bluff</i>		<t>turn:</t></v>
<v><i>blunder</i>		<t>turn:</t></v>
<v><i>blunt</i>		<t>turn:</t></v>
<v><i>blur</i>		<t>star:</t></v>
<v><i>blurt</i>		<t>turn:</t></v>
<v><i>blush</i>		<t>touch:</t></v>
<v><i>bluster</i>		<t>turn:</t></v>
<v><i>board</i>		<t>turn:</t></v>
<v><i>boast</i>		<t>turn:</t></v>
<v><i>boat</i>		<t>turn:</t></v>
<v><i>bob</i>		<t>mob:</t></v>
<v><i>bodge</i>		<t>lov:e</t></v>
<v><i>bog</i>		<t>beg:</t></v>
<v><i>boggle</i>		<t>lov:e</t></v>
<v><i>boil</i>		<t>turn:</t></v>
<v><i>bolster</i>		<t>turn:</t></v>
<v><i>bolt</i>		<t>turn:</t></v>
<v><i>bomb</i>		<t>turn:</t></v>
<v><i>bombard</i>		<t>turn:</t></v>
<v><i>bond</i>		<t>turn:</t></v>
<v><i>bone</i>		<t>lov:e</t></v>
<v><i>boo (at)</i>		<t>turn:</t></v>
<v><i>boob</i>		<t>turn:</t></v>
<v><i>book</i>		<t>turn:</t></v>
<v><i>boom</i>		<t>turn:</t></v>
<v><i>boomerang</i>		<t>turn:</t></v>
<v><i>boost</i>		<t>turn:</t></v>
<v><i>boot</i>		<t>turn:</t></v>
<v><i>bootleg</i>		<t>beg:</t></v>
<v><i>border</i>		<t>turn:</t></v>
<v><i>bore</i>		<t>lov:e</t></v>
<v><i>borrow (from)</i>		<t>turn:</t></v>
<v><i>boss</i>		<t>touch:</t></v>
<v><i>botanise</i>		<t>lov:e</t></v>
<v><i>botanize</i>		<t>lov:e</t></v>
<v><i>botch</i>		<t>touch:</t></v>
<v><i>bother</i>		<t>turn:</t></v>
<v><i>bottle</i>		<t>lov:e</t></v>
<v><i>bottle-feed</i>		<t>ble:ed</t></v>
<v><i>bottom</i>		<t>turn:</t></v>
<v><i>bounce</i>		<t>lov:e</t></v>
<v><i>bound</i>		<t>turn:</t></v>
<v><i>bow</i>		<t>turn:</t></v>
<v><i>bowl</i>		<t>turn:</t></v>
<v><i>box</i>		<t>touch:</t></v>
<v><i>brace</i>		<t>lov:e</t></v>
<v><i>bracket</i>		<t>turn:</t></v>
<v><i>brag</i>		<t>beg:</t></v>
<v><i>brake</i>		<t>lov:e</t></v>
<v><i>branch</i>		<t>touch:</t></v>
<v><i>brand</i>		<t>turn:</t></v>
<v><i>brandish</i>		<t>touch:</t></v>
<v><i>brave</i>		<t>lov:e</t></v>
<v><i>brawl</i>		<t>turn:</t></v>
<v><i>breach</i>		<t>touch:</t></v>
<v><i>break</i>		<t>sp:eak</t></v>
<v><i>breakfast</i>		<t>turn:</t></v>
<v><i>breast-feed</i>		<t>ble:ed</t></v>
<v><i>breathalyse</i>		<t>lov:e</t></v>
<v><i>breathalyze</i>		<t>lov:e</t></v>
<v><i>breathe</i>		<t>lov:e</t></v>
<v><i>breed</i>		<t>ble:ed</t></v>
<v><i>breeze</i>		<t>lov:e</t></v>
<v><i>brew</i>		<t>turn:</t></v>
<v><i>bribe</i>		<t>lov:e</t></v>
<v><i>brick in/off/up</i>		<t>turn:</t></v>
<v><i>bridge</i>		<t>lov:e</t></v>
<v><i>bridle</i>		<t>lov:e</t></v>
<v><i>brief</i>		<t>turn:</t></v>
<v><i>brighten</i>		<t>turn:</t></v>
<v><i>brim</i>		<t>slim:</t></v>
<v><i>bring</i>		<t>br:ing</t></v>
<v><i>bristle</i>		<t>lov:e</t></v>
<v><i>broach</i>		<t>touch:</t></v>
<v><i>broadcast</i>		<t>read:</t></v>
<v><i>broaden</i>		<t>turn:</t></v>
<v><i>broil</i>		<t>turn:</t></v>
<v><i>bronze</i>		<t>lov:e</t></v>
<v><i>brood</i>		<t>turn:</t></v>
<v><i>browbeat</i>		<t>turn:</t></v>
<v><i>brown</i>		<t>turn:</t></v>
<v><i>browse</i>		<t>lov:e</t></v>
<v><i>bruise</i>		<t>lov:e</t></v>
<v><i>brush</i>		<t>touch:</t></v>
<v><i>brutalise</i>		<t>lov:e</t></v>
<v><i>brutalize</i>		<t>lov:e</t></v>
<v><i>bubble</i>		<t>lov:e</t></v>
<v><i>buck</i>		<t>turn:</t></v>
<v><i>buckle</i>		<t>lov:e</t></v>
<v><i>bud</i>		<t>shred:</t></v>
<v><i>budge</i>		<t>lov:e</t></v>
<v><i>budget</i>		<t>turn:</t></v>
<v><i>buffer</i>		<t>turn:</t></v>
<v><i>bug</i>		<t>beg:</t></v>
<v><i>build</i>		<t>ben:d</t></v>
<v><i>bulge</i>		<t>lov:e</t></v>
<v><i>bulk up</i>		<t>turn:</t></v>
<v><i>bulldoze</i>		<t>lov:e</t></v>
<v><i>bully</i>		<t>carr:y</t></v>
<v><i>bum</i>		<t>slim:</t></v>
<v><i>bump</i>		<t>turn:</t></v>
<v><i>bunch</i>		<t>touch:</t></v>
<v><i>bundle</i>		<t>lov:e</t></v>
<v><i>bungle</i>		<t>lov:e</t></v>
<v><i>bunk</i>		<t>turn:</t></v>
<v><i>buoy</i>		<t>turn:</t></v>
<v><i>burble</i>		<t>lov:e</t></v>
<v><i>burden</i>		<t>turn:</t></v>
<v><i>burgeon</i>		<t>turn:</t></v>
<v><i>burglarise</i>		<t>lov:e</t></v>
<v><i>burglarize</i>		<t>lov:e</t></v>
<v><i>burgle</i>		<t>burg:le</t></v>
<v><i>burn</i>		<t>burn:</t></v>
<v><i>burnish</i>		<t>touch:</t></v>
<v><i>burp</i>		<t>turn:</t></v>
<v><i>burrow</i>		<t>turn:</t></v>
<v><i>burst</i>		<t>burst:</t></v>
<v><i>bury</i>		<t>carr:y</t></v>
<v><i>bus</i>		<t>bus:</t></v>
<v><i>busk</i>		<t>turn:</t></v>
<v><i>bust</i>		<t>turn:</t></v>
<v><i>bustle</i>		<t>lov:e</t></v>
<v><i>busy</i>		<t>carr:y</t></v>
<v><i>butcher</i>		<t>turn:</t></v>
<v><i>butt</i>		<t>turn:</t></v>
<v><i>butter</i>		<t>turn:</t></v>
<v><i>button</i>		<t>turn:</t></v>
<v><i>buttress</i>		<t>touch:</t></v>
<v><i>buy</i>		<t>b:uy</t></v>
<v><i>buzz</i>		<t>touch:</t></v>
<v><i>bypass</i>		<t>touch:</t></v>
<v><i>cable</i>		<t>lov:e</t></v>
<v><i>cache</i>		<t>lov:e</t></v>
<v><i>cackle</i>		<t>lov:e</t></v>
<v><i>cage</i>		<t>lov:e</t></v>
<v><i>cajole</i>		<t>lov:e</t></v>
<v><i>calculate</i>		<t>lov:e</t></v>
<v><i>calibrate</i>		<t>lov:e</t></v>
<v><i>calk</i>		<t>turn:</t></v>
<v><i>call</i>		<t>turn:</t></v>
<v><i>calm (down)</i>		<t>turn:</t></v>
<v><i>calumniate</i>		<t>lov:e</t></v>
<v><i>camp</i>		<t>turn:</t></v>
<v><i>campaign</i>		<t>turn:</t></v>
<v><i>can</i>		<t>pin:</t></v>
<v><i>canalise</i>		<t>lov:e</t></v>
<v><i>canalize</i>		<t>lov:e</t></v>
<v><i>cancel</i>		<t>turn:</t></v>
<v><i>cane</i>		<t>lov:e</t></v>
<v><i>cannibalise</i>		<t>lov:e</t></v>
<v><i>cannibalize</i>		<t>lov:e</t></v>
<v><i>canonise</i>		<t>lov:e</t></v>
<v><i>canonize</i>		<t>lov:e</t></v>
<v><i>cant</i>		<t>turn:</t></v>
<v><i>canvass</i>		<t>touch:</t></v>
<v><i>cap</i>		<t>stop:</t></v>
<v><i>caparison</i>		<t>turn:</t></v>
<v><i>caper</i>		<t>turn:</t></v>
<v><i>capitalise</i>		<t>lov:e</t></v>
<v><i>capitalize</i>		<t>lov:e</t></v>
<v><i>capitulate</i>		<t>lov:e</t></v>
<v><i>capsise</i>		<t>lov:e</t></v>
<v><i>capsize</i>		<t>lov:e</t></v>
<v><i>captain</i>		<t>turn:</t></v>
<v><i>caption</i>		<t>turn:</t></v>
<v><i>captivate</i>		<t>lov:e</t></v>
<v><i>capture</i>		<t>lov:e</t></v>
<v><i>care</i>		<t>lov:e</t></v>
<v><i>career</i>		<t>turn:</t></v>
<v><i>caress</i>		<t>touch:</t></v>
<v><i>carp</i>		<t>turn:</t></v>
<v><i>carpenter</i>		<t>turn:</t></v>
<v><i>carpet</i>		<t>turn:</t></v>
<v><i>carry</i>		<t>carr:y</t></v>
<v><i>cart</i>		<t>turn:</t></v>
<v><i>carve</i>		<t>lov:e</t></v>
<v><i>cascade</i>		<t>lov:e</t></v>
<v><i>case</i>		<t>lov:e</t></v>
<v><i>cash</i>		<t>touch:</t></v>
<v><i>cast</i>		<t>read:</t></v>
<v><i>castigate</i>		<t>lov:e</t></v>
<v><i>castrate</i>		<t>lov:e</t></v>
<v><i>catabolise</i>		<t>lov:e</t></v>
<v><i>catabolize</i>		<t>lov:e</t></v>
<v><i>catalyse</i>		<t>lov:e</t></v>
<v><i>catalyze</i>		<t>lov:e</t></v>
<v><i>catapult</i>		<t>turn:</t></v>
<v><i>catch</i>		<t>ca:tch</t></v>
<v><i>categorise</i>		<t>lov:e</t></v>
<v><i>categorize</i>		<t>lov:e</t></v>
<v><i>cater</i>		<t>turn:</t></v>
<v><i>catnap</i>		<t>stop:</t></v>
<v><i>cause</i>		<t>lov:e</t></v>
<v><i>cauterise</i>		<t>lov:e</t></v>
<v><i>cauterize</i>		<t>lov:e</t></v>
<v><i>caution</i>		<t>turn:</t></v>
<v><i>cave</i>		<t>lov:e</t></v>
<v><i>cavil</i>		<t>model:</t></v>
<v><i>cavort</i>		<t>turn:</t></v>
<v><i>cease</i>		<t>lov:e</t></v>
<v><i>celebrate</i>		<t>lov:e</t></v>
<v><i>cement</i>		<t>turn:</t></v>
<v><i>censor</i>		<t>turn:</t></v>
<v><i>censure</i>		<t>lov:e</t></v>
<v><i>center</i>		<t>turn:</t></v>
<v><i>centralise</i>		<t>lov:e</t></v>
<v><i>centralize</i>		<t>lov:e</t></v>
<v><i>centre</i>		<t>lov:e</t></v>
<v><i>certify</i>		<t>carr:y</t></v>
<v><i>chain</i>		<t>turn:</t></v>
<v><i>chain-smoke</i>		<t>lov:e</t></v>
<v><i>chair</i>		<t>turn:</t></v>
<v><i>chalk</i>		<t>turn:</t></v>
<v><i>challenge</i>		<t>lov:e</t></v>
<v><i>champion</i>		<t>turn:</t></v>
<v><i>chance</i>		<t>lov:e</t></v>
<v><i>change</i>		<t>lov:e</t></v>
<v><i>channel</i>		<t>model:</t></v>
<v><i>chant</i>		<t>turn:</t></v>
<v><i>char</i>		<t>star:</t></v>
<v><i>characterise</i>		<t>lov:e</t></v>
<v><i>characterize</i>		<t>lov:e</t></v>
<v><i>charge</i>		<t>lov:e</t></v>
<v><i>charm</i>		<t>turn:</t></v>
<v><i>chart</i>		<t>turn:</t></v>
<v><i>charter</i>		<t>turn:</t></v>
<v><i>chase</i>		<t>lov:e</t></v>
<v><i>chasten</i>		<t>turn:</t></v>
<v><i>chastise</i>		<t>lov:e</t></v>
<v><i>chat</i>		<t>permit:</t></v>
<v><i>chatter</i>		<t>turn:</t></v>
<v><i>cheapen</i>		<t>turn:</t></v>
<v><i>cheat</i>		<t>turn:</t></v>
<v><i>check</i>		<t>turn:</t></v>
<v><i>checker</i>		<t>turn:</t></v>
<v><i>checkmate</i>		<t>lov:e</t></v>
<v><i>cheek</i>		<t>turn:</t></v>
<v><i>cheep</i>		<t>turn:</t></v>
<v><i>cheer</i>		<t>turn:</t></v>
<v><i>chequer</i>		<t>turn:</t></v>
<v><i>cherish</i>		<t>touch:</t></v>
<v><i>chevy</i>		<t>carr:y</t></v>
<v><i>chew</i>		<t>turn:</t></v>
<v><i>chide</i>		<t>chid:e</t></v>
<v><i>chill</i>		<t>turn:</t></v>
<v><i>chime</i>		<t>lov:e</t></v>
<v><i>chip</i>		<t>stop:</t></v>
<v><i>chirp</i>		<t>turn:</t></v>
<v><i>chisel</i>		<t>model:</t></v>
<v><i>chivvy (fam)</i>		<t>carr:y</t></v>
<v><i>chivy (fam)</i>		<t>carr:y</t></v>
<v><i>choke</i>		<t>lov:e</t></v>
<v><i>chomp</i>		<t>turn:</t></v>
<v><i>choose</i>		<t>cho:ose</t></v>
<v><i>chop</i>		<t>turn:</t></v>
<v><i>chortle</i>		<t>lov:e</t></v>
<v><i>chorus</i>		<t>touch:</t></v>
<v><i>christen</i>		<t>turn:</t></v>
<v><i>chronicle</i>		<t>lov:e</t></v>
<v><i>chuck</i>		<t>turn:</t></v>
<v><i>chuckle</i>		<t>lov:e</t></v>
<v><i>chug</i>		<t>beg:</t></v>
<v><i>churn</i>		<t>turn:</t></v>
<v><i>cipher</i>		<t>turn:</t></v>
<v><i>circle</i>		<t>lov:e</t></v>
<v><i>circulate</i>		<t>lov:e</t></v>
<v><i>circumcise</i>		<t>lov:e</t></v>
<v><i>circumnavigate</i>		<t>lov:e</t></v>
<v><i>circumscribe</i>		<t>lov:e</t></v>
<v><i>circumvent</i>		<t>turn:</t></v>
<v><i>cite</i>		<t>lov:e</t></v>
<v><i>civilise</i>		<t>lov:e</t></v>
<v><i>civilize</i>		<t>lov:e</t></v>
<v><i>clack</i>		<t>turn:</t></v>
<v><i>claim</i>		<t>turn:</t></v>
<v><i>clamber</i>		<t>turn:</t></v>
<v><i>clamor</i>		<t>turn:</t></v>
<v><i>clamour</i>		<t>turn:</t></v>
<v><i>clamp</i>		<t>turn:</t></v>
<v><i>clank</i>		<t>turn:</t></v>
<v><i>clap</i>		<t>stop:</t></v>
<v><i>clarify</i>		<t>carr:y</t></v>
<v><i>clash</i>		<t>touch:</t></v>
<v><i>clasp</i>		<t>turn:</t></v>
<v><i>class</i>		<t>touch:</t></v>
<v><i>classify</i>		<t>carr:y</t></v>
<v><i>clatter</i>		<t>turn:</t></v>
<v><i>claw</i>		<t>turn:</t></v>
<v><i>clean</i>		<t>turn:</t></v>
<v><i>cleanse</i>		<t>lov:e</t></v>
<v><i>clear</i>		<t>turn:</t></v>
<v><i>cleave</i>		<t>:cleave</t></v>
<v><i>clench</i>		<t>touch:</t></v>
<v><i>clerk</i>		<t>turn:</t></v>
<v><i>click</i>		<t>turn:</t></v>
<v><i>climb</i>		<t>turn:</t></v>
<v><i>cling to</i>		<t>cl:ing_to</t></v>
<v><i>clink</i>		<t>turn:</t></v>
<v><i>clip</i>		<t>stop:</t></v>
<v><i>clobber</i>		<t>turn:</t></v>
<v><i>clock</i>		<t>turn:</t></v>
<v><i>clog</i>		<t>beg:</t></v>
<v><i>clone</i>		<t>lov:e</t></v>
<v><i>close</i>		<t>lov:e</t></v>
<v><i>clot</i>		<t>permit:</t></v>
<v><i>clothe</i>		<t>cloth:e</t></v>
<v><i>cloud</i>		<t>turn:</t></v>
<v><i>clout</i>		<t>turn:</t></v>
<v><i>clown (about, around)</i>		<t>turn:</t></v>
<v><i>club</i>		<t>mob:</t></v>
<v><i>clump</i>		<t>turn:</t></v>
<v><i>cluster</i>		<t>turn:</t></v>
<v><i>clutch</i>		<t>touch:</t></v>
<v><i>clutter</i>		<t>turn:</t></v>
<v><i>co-star</i>		<t>star:</t></v>
<v><i>coach</i>		<t>touch:</t></v>
<v><i>coagulate</i>		<t>lov:e</t></v>
<v><i>coalesce</i>		<t>lov:e</t></v>
<v><i>coarsen</i>		<t>turn:</t></v>
<v><i>coast</i>		<t>turn:</t></v>
<v><i>coat</i>		<t>turn:</t></v>
<v><i>coax</i>		<t>touch:</t></v>
<v><i>cobble</i>		<t>lov:e</t></v>
<v><i>cocoon</i>		<t>turn:</t></v>
<v><i>coddle</i>		<t>lov:e</t></v>
<v><i>code</i>		<t>lov:e</t></v>
<v><i>codify</i>		<t>carr:y</t></v>
<v><i>coerce</i>		<t>lov:e</t></v>
<v><i>coexist</i>		<t>turn:</t></v>
<v><i>cogitate</i>		<t>lov:e</t></v>
<v><i>cohabit</i>		<t>turn:</t></v>
<v><i>coil</i>		<t>turn:</t></v>
<v><i>coin</i>		<t>turn:</t></v>
<v><i>coincide</i>		<t>lov:e</t></v>
<v><i>cold-shoulder (someone)</i>		<t>turn:</t></v>
<v><i>collaborate</i>		<t>lov:e</t></v>
<v><i>collapse</i>		<t>lov:e</t></v>
<v><i>collar</i>		<t>turn:</t></v>
<v><i>collate</i>		<t>lov:e</t></v>
<v><i>collect</i>		<t>turn:</t></v>
<v><i>collide</i>		<t>lov:e</t></v>
<v><i>colonise</i>		<t>lov:e</t></v>
<v><i>colonize</i>		<t>lov:e</t></v>
<v><i>color</i>		<t>turn:</t></v>
<v><i>colour</i>		<t>turn:</t></v>
<v><i>comb</i>		<t>turn:</t></v>
<v><i>combat</i>		<t>turn:</t></v>
<v><i>combine (with)</i>		<t>lov:e</t></v>
<v><i>come</i>		<t>c:ome</t></v>
<v><i>comfort</i>		<t>turn:</t></v>
<v><i>command</i>		<t>turn:</t></v>
<v><i>commandeer</i>		<t>turn:</t></v>
<v><i>commemorate</i>		<t>lov:e</t></v>
<v><i>commence</i>		<t>lov:e</t></v>
<v><i>commend</i>		<t>turn:</t></v>
<v><i>comment</i>		<t>turn:</t></v>
<v><i>commercialise</i>		<t>lov:e</t></v>
<v><i>commercialize</i>		<t>lov:e</t></v>
<v><i>commiserate with</i>		<t>lov:e</t></v>