<?xml version="1.0" encoding="utf-8"?>

<!--
	conjugation-it.xml - Italian conjugation templates
	Copyright (C) 2010 Christophe Durville <http://polyglotte.tuxfamily.org>
	Copyright (C) 2015 Philippe Cora
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE conjugation-it [
	<!ELEMENT conjugation-it (template+)>
	<!ELEMENT template (infinitive, indicative, conditional, subjunctive, imperative, participle, gerund)>
	<!ATTLIST template name CDATA #REQUIRED>

	<!ELEMENT infinitive (infinitive-present)>
	<!ELEMENT indicative (present, imperfect, future, simple-past)>
	<!ELEMENT conditional (present)> 
	<!ELEMENT subjunctive (present, imperfect)>
	<!ELEMENT imperative (imperative-present)>
	<!ELEMENT participle (present-participle, past-participle)>
	<!ELEMENT gerund (present-gerund)>

	<!ELEMENT infinitive-present (p)>
	<!ELEMENT present (p, p, p, p, p, p)>
	<!ELEMENT present-gerund (p)>
	<!ELEMENT imperfect (p, p, p, p, p, p)>
	<!ELEMENT future (p, p, p, p, p, p)>
	<!ELEMENT simple-past (p, p, p, p, p, p)>
	<!ELEMENT imperative-present (p, p, p, p, p)>
	<!ELEMENT present-participle (p)>
	<!ELEMENT past-participle (p, p, p, p)>

	<!ELEMENT p (i*)>
	<!ELEMENT i (#PCDATA)>

]>

<conjugation-it >

<template name="am:are">  <!-- 1er groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>are</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>avo</i></p>
			<p><i>avi</i></p>
			<p><i>ava</i></p>
			<p><i>avamo</i></p>
			<p><i>avate</i></p>
			<p><i>avano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>ai</i></p>
			<p><i>asti</i></p>
			<p><i>ò</i></p>
			<p><i>ammo</i></p>
			<p><i>aste</i></p>
			<p><i>arono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</present>
		<imperfect>
			<p><i>assi</i></p>
			<p><i>assi</i></p>
			<p><i>asse</i></p>
			<p><i>assimo</i></p>
			<p><i>aste</i></p>
			<p><i>assero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>a</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>ate</i></p>
			<p><i>ino</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ante</i></p>
		</present-participle>
		<past-participle>
			<p><i>ato</i></p> 
			<p><i>ati</i></p>
			<p><i>ata</i></p>
			<p><i>ate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ando</i></p>
		</present-gerund>
	</gerund>
</template>



<template name="mang:iare">  <!-- 1er groupe (en iare) -->
	<infinitive>
		<infinitive-present>
			<p><i>iare</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>io</i></p>
			<p><i>i</i></p>
			<p><i>ia</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>iano</i></p>
		</present>
		<imperfect>
			<p><i>iavo</i></p>
			<p><i>iavi</i></p>
			<p><i>iava</i></p>
			<p><i>iavamo</i></p>
			<p><i>iavate</i></p>
			<p><i>iavano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>iai</i></p>
			<p><i>iasti</i></p>
			<p><i>iò</i></p>
			<p><i>iammo</i></p>
			<p><i>iaste</i></p>
			<p><i>iarono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</present>
		<imperfect>
			<p><i>iassi</i></p>
			<p><i>iassi</i></p>
			<p><i>iasse</i></p>
			<p><i>iassimo</i></p>
			<p><i>iaste</i></p> 
			<p><i>iassero</i></p> 
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>ia</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>iante</i></p>
		</present-participle>
		<past-participle>
			<p><i>iato</i></p>
			<p><i>iati</i></p>
			<p><i>iata</i></p>
			<p><i>iate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>iando</i></p>
		</present-gerund>
	</gerund>
</template>


<template name="stud:iare">  <!-- 1er groupe (en iare) -->
	<infinitive>
		<infinitive-present>
			<p><i>iare</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>io</i></p>
			<p><i>i</i></p>
			<p><i>ia</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>iano</i></p>
		</present>
		<imperfect>
			<p><i>iavo</i></p>
			<p><i>iavi</i></p>
			<p><i>iava</i></p>
			<p><i>iavamo</i></p>
			<p><i>iavate</i></p>
			<p><i>iavano</i></p>
		</imperfect>
		<future>
			<p><i>ierò</i></p>
			<p><i>ierai</i></p>
			<p><i>ierà</i></p>
			<p><i>ieremo</i></p>
			<p><i>ierete</i></p>
			<p><i>ieranno</i></p>
		</future>
		<simple-past>
			<p><i>iai</i></p>
			<p><i>iasti</i></p>
			<p><i>iò</i></p>
			<p><i>iammo</i></p>
			<p><i>iaste</i></p>
			<p><i>iarono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>ierei</i></p>
			<p><i>ieresti</i></p>
			<p><i>ierebbe</i></p>
			<p><i>ieremmo</i></p>
			<p><i>iereste</i></p>
			<p><i>ierebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</present>
		<imperfect>
			<p><i>iassi</i></p>
			<p><i>iassi</i></p>
			<p><i>iasse</i></p>
			<p><i>iassimo</i></p>
			<p><i>iaste</i></p>
			<p><i>iassero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>ia</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>iante</i></p>
		</present-participle>
		<past-participle>
			<p><i>iato</i></p>
			<p><i>iati</i></p>
			<p><i>iata</i></p>
			<p><i>iate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>iando</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="cred:ere">  <!-- 2eme groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>ere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>i</i></p>
			<p><i>e</i></p>
			<p><i>iamo</i></p>
			<p><i>ete</i></p>
			<p><i>ono</i></p>
		</present>
		<imperfect>
			<p><i>evo</i></p>
			<p><i>evi</i></p>
			<p><i>eva</i></p>
			<p><i>evamo</i></p>
			<p><i>evate</i></p>
			<p><i>evano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>etti</i><i>ei</i></p>
			<p><i>esti</i></p>
			<p><i>ette</i><i>é</i></p>
			<p><i>emmo</i></p>
			<p><i>este</i></p>
			<p><i>ettero</i><i>erono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>essi</i></p>
			<p><i>essi</i></p>
			<p><i>esse</i></p>
			<p><i>essimo</i></p>
			<p><i>este</i></p>
			<p><i>essero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ete</i></p>
			<p><i>ano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>uto</i></p>
			<p><i>uti</i></p>
			<p><i>uta</i></p>
			<p><i>ute</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="fin:ire">  <!-- 3eme groupe (b)-->
	<infinitive>
		<infinitive-present>
			<p><i>ire</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>isco</i></p>
			<p><i>isci</i></p>
			<p><i>isce</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>iscono</i></p>
		</present>
		<imperfect>
			<p><i>ivo</i></p>
			<p><i>ivi</i></p>
			<p><i>iva</i></p>
			<p><i>ivamo</i></p>
			<p><i>ivate</i></p>
			<p><i>ivano</i></p>
		</imperfect>
		<future>
			<p><i>irò</i></p>
			<p><i>irai</i></p>
			<p><i>irà</i></p>
			<p><i>iremo</i></p>
			<p><i>irete</i></p>
			<p><i>iranno</i></p>
		</future>
		<simple-past>
			<p><i>ii</i></p>
			<p><i>isti</i></p>
			<p><i>ì</i></p>
			<p><i>immo</i></p>
			<p><i>iste</i></p>
			<p><i>irono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>irei</i></p>
			<p><i>iresti</i></p>
			<p><i>irebbe</i></p>
			<p><i>iremmo</i></p>
			<p><i>ireste</i></p>
			<p><i>irebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>isca</i></p>
			<p><i>isca</i></p>
			<p><i>isca</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>iscano</i></p>
		</present>
		<imperfect>
			<p><i>issi</i></p>
			<p><i>issi</i></p>
			<p><i>isse</i></p>
			<p><i>issimo</i></p>
			<p><i>iste</i></p>
			<p><i>issero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>isci</i></p>
			<p><i>isca</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>iscano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>ito</i></p>
			<p><i>iti</i></p>
			<p><i>ita</i></p>
			<p><i>ite</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>


<template name="gioc:are">  <!-- 1er groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>are</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>hi</i></p>
			<p><i>a</i></p>
			<p><i>hiamo</i></p>
			<p><i>ate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>avo</i></p>
			<p><i>avi</i></p>
			<p><i>ava</i></p>
			<p><i>avamo</i></p>
			<p><i>avate</i></p>
			<p><i>avano</i></p>
		</imperfect>
		<future>
			<p><i>herò</i></p>
			<p><i>herai</i></p>
			<p><i>herà</i></p>
			<p><i>heremo</i></p>
			<p><i>herete</i></p>
			<p><i>heranno</i></p>
		</future>
		<simple-past>
			<p><i>ai</i></p>
			<p><i>asti</i></p>
			<p><i>ò</i></p>
			<p><i>ammo</i></p>
			<p><i>aste</i></p>
			<p><i>arono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>herei</i></p>
			<p><i>heresti</i></p>
			<p><i>herebbe</i></p>
			<p><i>heremmo</i></p>
			<p><i>hereste</i></p>
			<p><i>herebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>hi</i></p>
			<p><i>hi</i></p>
			<p><i>hi</i></p>
			<p><i>hiamo</i></p>
			<p><i>hiate</i></p>
			<p><i>hino</i></p>
		</present>
		<imperfect>
			<p><i>assi</i></p>
			<p><i>assi</i></p>
			<p><i>asse</i></p>
			<p><i>assimo</i></p>
			<p><i>aste</i></p>
			<p><i>assero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>a</i></p>
			<p><i>hi</i></p>
			<p><i>hiamo</i></p>
			<p><i>ate</i></p>
			<p><i>hino</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ante</i></p>
		</present-participle>
		<past-participle>
			<p><i>ato</i></p>
			<p><i>ati</i></p>
			<p><i>ata</i></p>
			<p><i>ate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ando</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="le:ggere">  <!-- 2eme groupe (exception) -->
	<infinitive>
		<infinitive-present>
			<p><i>ggere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>ggo</i></p>
			<p><i>ggi</i></p>
			<p><i>gge</i></p>
			<p><i>ggiamo</i></p>
			<p><i>ggete</i></p>
			<p><i>ggono</i></p>
		</present>
		<imperfect>
			<p><i>ggevo</i></p>
			<p><i>ggevi</i></p>
			<p><i>ggeva</i></p>
			<p><i>ggevamo</i></p>
			<p><i>ggevate</i></p>
			<p><i>ggevano</i></p>
		</imperfect>
		<future>
			<p><i>ggerò</i></p>
			<p><i>ggerai</i></p>
			<p><i>ggerà</i></p>
			<p><i>ggeremo</i></p>
			<p><i>ggerete</i></p>
			<p><i>ggeranno</i></p>
		</future>
		<simple-past>
			<p><i>ssi</i></p>
			<p><i>ggesti</i></p>
			<p><i>sse</i></p>
			<p><i>ggemmo</i></p>
			<p><i>ggeste</i></p>
			<p><i>ssero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>ggerei</i></p>
			<p><i>ggeresti</i></p>
			<p><i>ggerebbe</i></p>
			<p><i>ggeremmo</i></p>
			<p><i>ggereste</i></p>
			<p><i>ggerebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>gga</i></p>
			<p><i>gga</i></p>
			<p><i>gga</i></p>
			<p><i>ggiamo</i></p>
			<p><i>ggiate</i></p>
			<p><i>ggano</i></p>
		</present>
		<imperfect>
			<p><i>ggessi</i></p>
			<p><i>ggessi</i></p>
			<p><i>ggesse</i></p>
			<p><i>ggessimo</i></p>
			<p><i>ggeste</i></p>
			<p><i>ggessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>ggi</i></p>
			<p><i>gga</i></p>
			<p><i>ggiamo</i></p>
			<p><i>ggete</i></p>
			<p><i>ggano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ggente</i></p>
		</present-participle>
		<past-participle>
			<p><i>tto</i></p>
			<p><i>tti</i></p>
			<p><i>tta</i></p>
			<p><i>tte</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ggendo</i></p>
		</present-gerund>
	</gerund>
</template>



<template name="m:ettere">  
	<infinitive>
		<infinitive-present>
			<p><i>ettere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>etto</i></p>
			<p><i>etti</i></p>
			<p><i>ette</i></p>
			<p><i>ettiamo</i></p>
			<p><i>ettete</i></p>
			<p><i>ettono</i></p>
		</present>
		<imperfect>
			<p><i>ettevo</i></p>
			<p><i>ettevi</i></p>
			<p><i>etteva</i></p>
			<p><i>ettevamo</i></p>
			<p><i>ettevate</i></p>
			<p><i>ettevano</i></p>
		</imperfect>
		<future>
			<p><i>etterò</i></p>
			<p><i>etterai</i></p>
			<p><i>etterà</i></p>
			<p><i>etteremo</i></p>
			<p><i>etterete</i></p>
			<p><i>etteranno</i></p>
		</future>
		<simple-past>
			<p><i>isi</i></p>
			<p><i>ettesti</i></p>
			<p><i>ise</i></p>
			<p><i>ettemmo</i></p>
			<p><i>etteste</i></p>
			<p><i>isero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>etterei</i></p>
			<p><i>etteresti</i></p>
			<p><i>etterebbe</i></p>
			<p><i>etteremmo</i></p>
			<p><i>ettereste</i></p>
			<p><i>etterebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>etta</i></p>
			<p><i>etta</i></p>
			<p><i>etta</i></p>
			<p><i>ettiamo</i></p>
			<p><i>ettiate</i></p>
			<p><i>ettano</i></p>
		</present>
		<imperfect>
			<p><i>ettessi</i></p>
			<p><i>ettessi</i></p>
			<p><i>ettesse</i></p>
			<p><i>ettessimo</i></p>
			<p><i>etteste</i></p>
			<p><i>ettessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>etti</i></p>
			<p><i>etta</i></p>
			<p><i>ettiamo</i></p>
			<p><i>ettete</i></p>
			<p><i>ettano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ettente</i></p>
		</present-participle>
		<past-participle>
			<p><i>esso</i></p>
			<p><i>essi</i></p>
			<p><i>essa</i></p>
			<p><i>esse</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ettendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="piac:ere">  <!-- 2eme groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>ere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>cio</i></p>
			<p><i>i</i></p>
			<p><i>e</i></p>
			<p><i>iamo</i><i>ciamo</i></p>
			<p><i>ete</i></p>
			<p><i>iono</i><i>ciono</i></p>
		</present>
		<imperfect>
			<p><i>evo</i></p>
			<p><i>evi</i></p>
			<p><i>eva</i></p>
			<p><i>evamo</i></p>
			<p><i>evate</i></p>
			<p><i>evano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>qui</i></p>
			<p><i>esti</i></p>
			<p><i>que</i></p>
			<p><i>emmo</i></p>
			<p><i>este</i></p>
			<p><i>quero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>cia</i></p>
			<p><i>cia</i></p>
			<p><i>cia</i></p>
			<p><i>ciamo</i><i>iamo</i></p>
			<p><i>ciate</i><i>iate</i></p>
			<p><i>ciano</i></p>
		</present>
		<imperfect>
			<p><i>essi</i></p>
			<p><i>essi</i></p>
			<p><i>esse</i></p>
			<p><i>essimo</i></p>
			<p><i>este</i></p>
			<p><i>essero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>cia</i></p>
			<p><i>ciamo</i></p>
			<p><i>ete</i></p>
			<p><i>iano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>iuto</i></p>
			<p><i>iuti</i></p>
			<p><i>iuta</i></p>
			<p><i>iute</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="part:ire">  <!-- 3eme groupe (a)-->
	<infinitive>
		<infinitive-present>
			<p><i>ire</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>i</i></p>
			<p><i>e</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>ono</i></p>
		</present>
		<imperfect>
			<p><i>ivo</i></p>
			<p><i>ivi</i></p>
			<p><i>iva</i></p>
			<p><i>ivamo</i></p>
			<p><i>ivate</i></p>
			<p><i>ivano</i></p>
		</imperfect>
		<future>
			<p><i>irò</i></p>
			<p><i>irai</i></p>
			<p><i>irà</i></p>
			<p><i>iremo</i></p>
			<p><i>irete</i></p>
			<p><i>iranno</i></p>
		</future>
		<simple-past>
			<p><i>ii</i></p>
			<p><i>isti</i></p>
			<p><i>ì</i></p>
			<p><i>immo</i></p>
			<p><i>iste</i></p>
			<p><i>irono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>irei</i></p>
			<p><i>iresti</i></p>
			<p><i>irebbe</i></p>
			<p><i>iremmo</i></p>
			<p><i>ireste</i></p>
			<p><i>irebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>issi</i></p>
			<p><i>issi</i></p>
			<p><i>isse</i></p>
			<p><i>issimo</i></p>
			<p><i>iste</i></p>
			<p><i>issero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>ano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>ito</i></p>
			<p><i>iti</i></p>
			<p><i>ita</i></p>
			<p><i>ite</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>





<!-- ____________________________ -->
<!-- generici -->
<template name="pa:rire"> 

	<infinitive>
		<infinitive-present>
			<p><i>rire</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>io</i></p>
			<p><i>ri</i></p>
			<p><i>re</i></p>
			<p><i>riamo</i></p>
			<p><i>rite</i></p>
			<p><i>iono</i></p>
		</present>
		<imperfect>
			<p><i>rivo</i></p>
			<p><i>rivi</i></p>
			<p><i>riva</i></p>
			<p><i>rivamo</i></p>
			<p><i>rivate</i></p>
			<p><i>rivano</i></p>
		</imperfect>
		<future>
			<p><i>rirò</i></p>
			<p><i>rirai</i></p>
			<p><i>rirà</i></p>
			<p><i>riremo</i></p>
			<p><i>rirete</i></p>
			<p><i>riranno</i></p>
		</future>
		<simple-past>
			<p><i>rvi</i></p>
			<p><i>risti</i></p>
			<p><i>rve</i></p>
			<p><i>rimmo</i></p>
			<p><i>riste</i></p>
			<p><i>rvero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>rirei</i></p>
			<p><i>riresti</i></p>
			<p><i>rirebbe</i></p>
			<p><i>riremmo</i></p>
			<p><i>rireste</i></p>
			<p><i>rirebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>ia</i></p>
			<p><i>ia</i></p>
			<p><i>ia</i></p>
			<p><i>riamo</i></p>
			<p><i>riate</i></p>
			<p><i>iano</i></p>
		</present>
		<imperfect>
			<p><i>rissi</i></p>
			<p><i>rissi</i></p>
			<p><i>risse</i></p>
			<p><i>rissimo</i></p>
			<p><i>riste</i></p>
			<p><i>rissero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>ri</i></p>
			<p><i>ia</i></p>
			<p><i>riamo</i></p>
			<p><i>rite</i></p>
			<p><i>iano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>rente</i></p>
		</present-participle>
		<past-participle>
			<p><i>rso</i></p>
			<p><i>rsi</i></p>
			<p><i>rsa</i></p>
			<p><i>rse</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>rendo</i></p>
		</present-gerund>
	</gerund>
</template>





<!-- ____________________________ -->
<!-- irregolari -->


<template name="acclu:dere"> 
	<infinitive>
		<infinitive-present>
			<p><i>dere</i></p>
		</infinitive-present>
		</infinitive>
	<indicative>
		<present>
			<p><i>do</i></p>
			<p><i>di</i></p>
			<p><i>de</i></p>
			<p><i>diamo</i></p>
			<p><i>dete</i></p>
			<p><i>donno</i></p>
		</present>
		<imperfect>
			<p><i>devo</i></p>
			<p><i>devi</i></p>
			<p><i>deva</i></p>
			<p><i>devamo</i></p>
			<p><i>devate</i></p>
			<p><i>devano</i></p>
		</imperfect>
		<future>
			<p><i>derò</i></p>
			<p><i>derai</i></p>
			<p><i>derà</i></p>
			<p><i>deremo</i></p>
			<p><i>derete</i></p>
			<p><i>deranno</i></p>
		</future>
		<simple-past>
			<p><i>si</i></p>
			<p><i>desti</i></p>
			<p><i>se</i></p>
			<p><i>demmo</i></p>
			<p><i>deste</i></p>
			<p><i>sero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>derei</i></p>
			<p><i>deresti</i></p>
			<p><i>derebbe</i></p>
			<p><i>deremmo</i></p>
			<p><i>dereste</i></p>
			<p><i>derebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>da</i></p>
			<p><i>da</i></p>
			<p><i>da</i></p>
			<p><i>diamo</i></p>
			<p><i>diate</i></p>
			<p><i>dano</i></p>
		</present>
		<imperfect>
			<p><i>dessi</i></p>
			<p><i>dessi</i></p>
			<p><i>desse</i></p>
			<p><i>dessimo</i></p>
			<p><i>deste</i></p>
			<p><i>dessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>di</i></p>
			<p><i>da</i></p>
			<p><i>diamo</i></p>
			<p><i>dete</i></p>
			<p><i>dano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>dente</i></p>
		</present-participle>
		<past-participle>
			<p><i>so</i></p>
			<p><i>si</i></p>
			<p><i>sa</i></p>
			<p><i>se</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>dendo</i></p>
		</present-gerund>
	</gerund>
</template>





<template name="accor:gere">  <!-- 2eme groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>gere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>go</i></p>
			<p><i>gi</i></p>
			<p><i>ge</i></p>
			<p><i>giamo</i></p>
			<p><i>gete</i></p>
			<p><i>gono</i></p>
		</present>
		<imperfect>
			<p><i>gevo</i></p>
			<p><i>gevi</i></p>
			<p><i>geva</i></p>
			<p><i>gevamo</i></p>
			<p><i>gevate</i></p>
			<p><i>gevano</i></p>
		</imperfect>
		<future>
			<p><i>gerò</i></p>
			<p><i>gerai</i></p>
			<p><i>gerà</i></p>
			<p><i>geremo</i></p>
			<p><i>gerete</i></p>
			<p><i>geranno</i></p>
		</future>
		<simple-past>
			<p><i>si</i><i>ei</i></p>
			<p><i>gesti</i></p>
			<p><i>se</i><i>é</i></p>
			<p><i>semmo</i></p>
			<p><i>seste</i></p>
			<p><i>sero</i><i>erono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>gerei</i></p>
			<p><i>geresti</i></p>
			<p><i>gerebbe</i></p>
			<p><i>geremmo</i></p>
			<p><i>gereste</i></p>
			<p><i>gerebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>ga</i></p>
			<p><i>ga</i></p>
			<p><i>ga</i></p>
			<p><i>giamo</i></p>
			<p><i>giate</i></p>
			<p><i>gano</i></p>
		</present>
		<imperfect>
			<p><i>gessi</i></p>
			<p><i>gessi</i></p>
			<p><i>gesse</i></p>
			<p><i>gessimo</i></p>
			<p><i>geste</i></p>
			<p><i>gessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>gi</i></p>
			<p><i>ga</i></p>
			<p><i>giamo</i></p>
			<p><i>gete</i></p>
			<p><i>gano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>gente</i></p>
		</present-participle>
		<past-participle>
			<p><i>to</i></p>
			<p><i>ti</i></p>
			<p><i>ta</i></p>
			<p><i>te</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>gendo</i></p>
		</present-gerund>
	</gerund>
</template>


<template name=":andare">  <!-- 1er groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>andare</i></p>
		</infinitive-present>
		</infinitive>
	<indicative>
		<present>
			<p><i>vado</i></p>
			<p><i>vai</i></p>
			<p><i>va</i></p>
			<p><i>andiamo</i></p>
			<p><i>andate</i></p>
			<p><i>vanno</i></p>
		</present>
		<imperfect>
			<p><i>andavo</i></p>
			<p><i>andavi</i></p>
			<p><i>andava</i></p>
			<p><i>andavamo</i></p>
			<p><i>andavate</i></p>
			<p><i>andavano</i></p>
		</imperfect>
		<future>
			<p><i>andrò</i></p>
			<p><i>andrai</i></p>
			<p><i>andrà</i></p>
			<p><i>andremo</i></p>
			<p><i>andrete</i></p>
			<p><i>andranno</i></p>
		</future>
		<simple-past>
			<p><i>andai</i></p>
			<p><i>andasti</i></p>
			<p><i>andò</i></p>
			<p><i>andammo</i></p>
			<p><i>andaste</i></p>
			<p><i>andarono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>andrei</i></p>
			<p><i>andresti</i></p>
			<p><i>andrebbe</i></p>
			<p><i>andremmo</i></p>
			<p><i>andreste</i></p>
			<p><i>andrebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>vada</i></p>
			<p><i>vada</i></p>
			<p><i>vada</i></p>
			<p><i>andiamo</i></p>
			<p><i>andiate</i></p>
			<p><i>vadano</i></p>
		</present>
		<imperfect>
			<p><i>andassi</i></p>
			<p><i>andassi</i></p>
			<p><i>andasse</i></p>
			<p><i>andassimo</i></p>
			<p><i>andaste</i></p>
			<p><i>andassero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>va</i><i>vai</i><i>và</i></p>
			<p><i>vada</i></p>
			<p><i>andiamo</i></p>
			<p><i>andate</i></p>
			<p><i>vadano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>andante</i></p>
		</present-participle>
		<past-participle>
			<p><i>andato</i></p>
			<p><i>andati</i></p>
			<p><i>andata</i></p>
			<p><i>andate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>andando</i></p>
		</present-gerund>
	</gerund>
</template>




<template name="ap:rire">  <!-- 1er groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>rire</i></p>
		</infinitive-present>
		</infinitive>
	<indicative>
		<present>
			<p><i>ro</i></p>
			<p><i>ri</i></p>
			<p><i>re</i></p>
			<p><i>riamo</i></p>
			<p><i>rite</i></p>
			<p><i>rono</i></p>
		</present>
		<imperfect>
			<p><i>rivo</i></p>
			<p><i>rivi</i></p>
			<p><i>riva</i></p>
			<p><i>rivamo</i></p>
			<p><i>rivate</i></p>
			<p><i>rivano</i></p>
		</imperfect>
		<future>
			<p><i>rirò</i></p>
			<p><i>rirai</i></p>
			<p><i>rirà</i></p>
			<p><i>riremo</i></p>
			<p><i>rirete</i></p>
			<p><i>riranno</i></p>
		</future>
		<simple-past>
			<p><i>rii</i></p>
			<p><i>risti</i></p>
			<p><i>rì</i></p>
			<p><i>rimmo</i></p>
			<p><i>riste</i></p>
			<p><i>rirono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>rirei</i></p>
			<p><i>riresti</i></p>
			<p><i>rirebbe</i></p>
			<p><i>riremmo</i></p>
			<p><i>rireste</i></p>
			<p><i>rirebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>ra</i></p>
			<p><i>ra</i></p>
			<p><i>ra</i></p>
			<p><i>riamo</i></p>
			<p><i>riate</i></p>
			<p><i>rano</i></p>
		</present>
		<imperfect>
			<p><i>rissi</i></p>
			<p><i>rissi</i></p>
			<p><i>risse</i></p>
			<p><i>rissimo</i></p>
			<p><i>riste</i></p>
			<p><i>rissero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>