<?xml version="1.0" encoding='utf-8'?>

<!--
	verbs-fr.xml - List of French verbs with their conjugation template
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE verbs-fr [
	<!ELEMENT verbs-fr (v+)>
	<!ELEMENT v (i, t, aspirate-h?)>
	<!ELEMENT i (#PCDATA)>  <!-- infinitive -->
	<!ELEMENT t (#PCDATA)>	<!-- template (radical:termination) -->
	<!ELEMENT aspirate-h EMPTY>  <!-- useful for verbs starting with h -->
]>

<!--
	The <v> lines are sorted with this filter:
	env LANG=en_US.utf8 sort -f
-->

<verbs-fr>

<v><i>abaisser</i>		<t>aim:er</t></v>
<v><i>abandonner</i>		<t>aim:er</t></v>
<v><i>abasourdir</i>		<t>fin:ir</t></v>
<v><i>abâtardir</i>		<t>fin:ir</t></v>
<v><i>abattre</i>		<t>bat:tre</t></v>
<v><i>abcéder</i>		<t>c:éder</t></v>
<v><i>abdiquer</i>		<t>aim:er</t></v>
<v><i>aberrer</i>		<t>aim:er</t></v>
<v><i>abêtir</i>		<t>fin:ir</t></v>
<v><i>abhorrer</i>		<t>aim:er</t></v>
<v><i>abîmer</i>		<t>aim:er</t></v>
<v><i>abjurer</i>		<t>aim:er</t></v>
<v><i>ablater</i>		<t>aim:er</t></v>
<v><i>abloquer</i>		<t>aim:er</t></v>
<v><i>abolir</i>		<t>fin:ir</t></v>
<v><i>abominer</i>		<t>aim:er</t></v>
<v><i>abonder</i>		<t>aim:er</t></v>
<v><i>abonner</i>		<t>aim:er</t></v>
<v><i>abonnir</i>		<t>fin:ir</t></v>
<v><i>aborder</i>		<t>aim:er</t></v>
<v><i>aboucher</i>		<t>aim:er</t></v>
<v><i>abouler</i>		<t>aim:er</t></v>
<v><i>abouter</i>		<t>aim:er</t></v>
<v><i>aboutir</i>		<t>fin:ir</t></v>
<v><i>aboyer</i>		<t>netto:yer</t></v>
<v><i>abraser</i>		<t>aim:er</t></v>
<v><i>abréger</i>		<t>abr:éger</t></v>
<v><i>abreuver</i>		<t>aim:er</t></v>
<v><i>abrévier</i>		<t>aim:er</t></v>
<v><i>abricoter</i>		<t>aim:er</t></v>
<v><i>abrier</i>		<t>aim:er</t></v>
<v><i>abriter</i>		<t>aim:er</t></v>
<v><i>abroger</i>		<t>man:ger</t></v>
<v><i>abrutir</i>		<t>fin:ir</t></v>
<v><i>absenter</i>		<t>aim:er</t></v>
<v><i>absorber</i>		<t>aim:er</t></v>
<v><i>absoudre</i>		<t>abso:udre</t></v>
<v><i>abstenir</i>		<t>t:enir</t></v>
<v><i>abstraire</i>		<t>extra:ire</t></v>
<v><i>abuser</i>		<t>aim:er</t></v>
<v><i>accabler</i>		<t>aim:er</t></v>
<v><i>accaparer</i>		<t>aim:er</t></v>
<v><i>accastiller</i>		<t>aim:er</t></v>
<v><i>accéder</i>		<t>c:éder</t></v>
<v><i>accélérer</i>		<t>réf:érer</t></v>
<v><i>accentuer</i>		<t>aim:er</t></v>
<v><i>accepter</i>		<t>aim:er</t></v>
<v><i>accessoiriser</i>		<t>aim:er</t></v>
<v><i>accidenter</i>		<t>aim:er</t></v>
<v><i>acclamer</i>		<t>aim:er</t></v>
<v><i>acclimater</i>		<t>aim:er</t></v>
<v><i>accointer</i>		<t>aim:er</t></v>
<v><i>accoler</i>		<t>aim:er</t></v>
<v><i>accommoder</i>		<t>aim:er</t></v>
<v><i>accompagner</i>		<t>aim:er</t></v>
<v><i>accomplir</i>		<t>fin:ir</t></v>
<v><i>accorder</i>		<t>aim:er</t></v>
<v><i>accorer</i>		<t>aim:er</t></v>
<v><i>accoster</i>		<t>aim:er</t></v>
<v><i>accoter</i>		<t>aim:er</t></v>
<v><i>accoucher</i>		<t>aim:er</t></v>
<v><i>accouder</i>		<t>aim:er</t></v>
<v><i>accouer</i>		<t>aim:er</t></v>
<v><i>accoupler</i>		<t>aim:er</t></v>
<v><i>accourcir</i>		<t>fin:ir</t></v>
<v><i>accourir</i>		<t>cour:ir</t></v>
<v><i>accoutrer</i>		<t>aim:er</t></v>
<v><i>accoutumer</i>		<t>aim:er</t></v>
<v><i>accréditer</i>		<t>aim:er</t></v>
<v><i>accréter</i>		<t>décr:éter</t></v>
<v><i>accrocher</i>		<t>aim:er</t></v>
<v><i>accroître</i>		<t>accr:oître</t></v>
<v><i>accroupir</i>		<t>fin:ir</t></v>
<v><i>accueillir</i>		<t>cueill:ir</t></v>
<v><i>acculer</i>		<t>aim:er</t></v>
<v><i>acculturer</i>		<t>aim:er</t></v>
<v><i>accumuler</i>		<t>aim:er</t></v>
<v><i>accuser</i>		<t>aim:er</t></v>
<v><i>acérer</i>		<t>réf:érer</t></v>
<v><i>acétifier</i>		<t>aim:er</t></v>
<v><i>acétyler</i>		<t>aim:er</t></v>
<v><i>achalander</i>		<t>aim:er</t></v>
<v><i>achaler</i>		<t>aim:er</t></v>
<v><i>acharner</i>		<t>aim:er</t></v>
<v><i>acheminer</i>		<t>aim:er</t></v>
<v><i>acheter</i>		<t>ach:eter</t></v>
<v><i>achever</i>		<t>l:ever</t></v>
<v><i>achopper</i>		<t>aim:er</t></v>
<v><i>achromatiser</i>		<t>aim:er</t></v>
<v><i>acidifier</i>		<t>aim:er</t></v>
<v><i>aciduler</i>		<t>aim:er</t></v>
<v><i>aciérer</i>		<t>réf:érer</t></v>
<v><i>aciseler</i>		<t>p:eler</t></v>
<v><i>acoquiner</i>		<t>aim:er</t></v>
<v><i>acquérir</i>		<t>acqu:érir</t></v>
<v><i>acquiescer</i>		<t>pla:cer</t></v>
<v><i>acquitter</i>		<t>aim:er</t></v>
<v><i>acter</i>			<t>aim:er</t></v>
<v><i>actionner</i>		<t>aim:er</t></v>
<v><i>activer</i>		<t>aim:er</t></v>
<v><i>actualiser</i>		<t>aim:er</t></v>
<v><i>adapter</i>		<t>aim:er</t></v>
<v><i>additionner</i>		<t>aim:er</t></v>
<v><i>adhérer</i>		<t>réf:érer</t></v>
<v><i>adjectiver</i>		<t>aim:er</t></v>
<v><i>adjectiviser</i>		<t>aim:er</t></v>
<v><i>adjoindre</i>		<t>crai:ndre</t></v>
<v><i>adjuger</i>		<t>man:ger</t></v>
<v><i>adjurer</i>		<t>aim:er</t></v>
<v><i>admettre</i>		<t>m:ettre</t></v>
<v><i>administrer</i>		<t>aim:er</t></v>
<v><i>admirer</i>		<t>aim:er</t></v>
<v><i>admonester</i>		<t>aim:er</t></v>
<v><i>adonner</i>		<t>aim:er</t></v>
<v><i>adopter</i>		<t>aim:er</t></v>
<v><i>adorer</i>		<t>aim:er</t></v>
<v><i>adosser</i>		<t>aim:er</t></v>
<v><i>adouber</i>		<t>aim:er</t></v>
<v><i>adoucir</i>		<t>fin:ir</t></v>
<v><i>adresser</i>		<t>aim:er</t></v>
<v><i>adsorber</i>		<t>aim:er</t></v>
<v><i>aduler</i>		<t>aim:er</t></v>
<v><i>adultérer</i>		<t>réf:érer</t></v>
<v><i>advenir</i>		<t>adv:enir</t></v>
<v><i>aérer</i>			<t>réf:érer</t></v>
<v><i>affabuler</i>		<t>aim:er</t></v>
<v><i>affadir</i>		<t>fin:ir</t></v>
<v><i>affaiblir</i>		<t>fin:ir</t></v>
<v><i>affairer</i>		<t>aim:er</t></v>
<v><i>affaisser</i>		<t>aim:er</t></v>
<v><i>affaler</i>		<t>aim:er</t></v>
<v><i>affamer</i>		<t>aim:er</t></v>
<v><i>afféager</i>		<t>man:ger</t></v>
<v><i>affecter</i>		<t>aim:er</t></v>
<v><i>affectionner</i>		<t>aim:er</t></v>
<v><i>affermer</i>		<t>aim:er</t></v>
<v><i>affermir</i>		<t>fin:ir</t></v>
<v><i>afficher</i>		<t>aim:er</t></v>
<v><i>affiler</i>		<t>aim:er</t></v>
<v><i>affilier</i>		<t>aim:er</t></v>
<v><i>affiner</i>		<t>aim:er</t></v>
<v><i>affirmer</i>		<t>aim:er</t></v>
<v><i>affleurer</i>		<t>aim:er</t></v>
<v><i>affliger</i>		<t>man:ger</t></v>
<v><i>afflouer</i>		<t>aim:er</t></v>
<v><i>affluer</i>		<t>aim:er</t></v>
<v><i>affoler</i>		<t>aim:er</t></v>
<v><i>affouager</i>		<t>man:ger</t></v>
<v><i>affouiller</i>		<t>aim:er</t></v>
<v><i>affourager</i>		<t>man:ger</t></v>
<v><i>affourcher</i>		<t>aim:er</t></v>
<v><i>affourrager</i>		<t>man:ger</t></v>
<v><i>affranchir</i>		<t>fin:ir</t></v>
<v><i>affréter</i>		<t>décr:éter</t></v>
<v><i>affriander</i>		<t>aim:er</t></v>
<v><i>affricher</i>		<t>aim:er</t></v>
<v><i>affrioler</i>		<t>aim:er</t></v>
<v><i>affriter</i>		<t>aim:er</t></v>
<v><i>affronter</i>		<t>aim:er</t></v>
<v><i>affruiter</i>		<t>aim:er</t></v>
<v><i>affubler</i>		<t>aim:er</t></v>
<v><i>affurer</i>		<t>aim:er</t></v>
<v><i>affûter</i>		<t>aim:er</t></v>
<v><i>africaniser</i>		<t>aim:er</t></v>
<v><i>agacer</i>		<t>pla:cer</t></v>
<v><i>agencer</i>		<t>pla:cer</t></v>
<v><i>agender</i>		<t>aim:er</t></v>
<v><i>agenouiller</i>		<t>aim:er</t></v>
<v><i>agglomérer</i>		<t>réf:érer</t></v>
<v><i>agglutiner</i>		<t>aim:er</t></v>
<v><i>aggraver</i>		<t>aim:er</t></v>
<v><i>agioter</i>		<t>aim:er</t></v>
<v><i>agir</i>			<t>fin:ir</t></v>
<v><i>agiter</i>		<t>aim:er</t></v>
<v><i>agneler</i>		<t>app:eler</t></v>
<v><i>agoniser</i>		<t>aim:er</t></v>
<v><i>agrafer</i>		<t>aim:er</t></v>
<v><i>agrainer</i>		<t>aim:er</t></v>
<v><i>agrandir</i>		<t>fin:ir</t></v>
<v><i>agréer</i>		<t>aim:er</t></v>
<v><i>agréger</i>		<t>abr:éger</t></v>
<v><i>agrémenter</i>		<t>aim:er</t></v>
<v><i>agresser</i>		<t>aim:er</t></v>
<v><i>agricher</i>		<t>aim:er</t></v>
<v><i>agriffer</i>		<t>aim:er</t></v>
<v><i>agripper</i>		<t>aim:er</t></v>
<v><i>aguerrir</i>		<t>fin:ir</t></v>
<v><i>aguicher</i>		<t>aim:er</t></v>
<v><i>ahaner</i>		<t>aim:er</t></v>
<v><i>ahurir</i>		<t>fin:ir</t></v>
<v><i>aider</i>			<t>aim:er</t></v>
<v><i>aigrir</i>		<t>fin:ir</t></v>
<v><i>aiguiller</i>		<t>aim:er</t></v>
<v><i>aiguilleter</i>		<t>j:eter</t></v>
<v><i>aiguillonner</i>		<t>aim:er</t></v>
<v><i>aiguiser</i>		<t>aim:er</t></v>
<v><i>ailler</i>		<t>aim:er</t></v>
<v><i>aimanter</i>		<t>aim:er</t></v>
<v><i>aimer</i>			<t>aim:er</t></v>
<v><i>airer</i>			<t>aim:er</t></v>
<v><i>ajointer</i>		<t>aim:er</t></v>
<v><i>ajourer</i>		<t>aim:er</t></v>
<v><i>ajourner</i>		<t>aim:er</t></v>
<v><i>ajouter</i>		<t>aim:er</t></v>
<v><i>ajuster</i>		<t>aim:er</t></v>
<v><i>alambiquer</i>		<t>aim:er</t></v>
<v><i>alanguir</i>		<t>fin:ir</t></v>
<v><i>alarmer</i>		<t>aim:er</t></v>
<v><i>alcaliniser</i>		<t>aim:er</t></v>
<v><i>alcaliser</i>		<t>aim:er</t></v>
<v><i>alcooliser</i>		<t>aim:er</t></v>
<v><i>alentir</i>		<t>fin:ir</t></v>
<v><i>alerter</i>		<t>aim:er</t></v>
<v><i>aléser</i>		<t>l:éser</t></v>
<v><i>aleviner</i>		<t>aim:er</t></v>
<v><i>aliéner</i>		<t>ali:éner</t></v>
<v><i>aligner</i>		<t>aim:er</t></v>
<v><i>alimenter</i>		<t>aim:er</t></v>
<v><i>aliter</i>		<t>aim:er</t></v>
<v><i>allaiter</i>		<t>aim:er</t></v>
<v><i>allécher</i>		<t>s:écher</t></v>
<v><i>alléger</i>		<t>abr:éger</t></v>
<v><i>allégir</i>		<t>fin:ir</t></v>
<v><i>allégoriser</i>		<t>aim:er</t></v>
<v><i>alléguer</i>		<t>l:éguer</t></v>
<v><i>aller</i>			<t>:aller</t></v>
<v><i>allier</i>		<t>aim:er</t></v>
<v><i>allonger</i>		<t>man:ger</t></v>
<v><i>allotir</i>		<t>fin:ir</t></v>
<v><i>allouer</i>		<t>aim:er</t></v>
<v><i>allumer</i>		<t>aim:er</t></v>
<v><i>alluvionner</i>		<t>aim:er</t></v>
<v><i>alourdir</i>		<t>fin:ir</t></v>
<v><i>alpaguer</i>		<t>aim:er</t></v>
<v><i>alphabétiser</i>		<t>aim:er</t></v>
<v><i>altérer</i>		<t>réf:érer</t></v>
<v><i>alterner</i>		<t>aim:er</t></v>
<v><i>aluminer</i>		<t>aim:er</t></v>
<v><i>aluner</i>		<t>aim:er</t></v>
<v><i>alunir</i>		<t>fin:ir</t></v>
<v><i>amadouer</i>		<t>aim:er</t></v>
<v><i>amaigrir</i>		<t>fin:ir</t></v>
<v><i>amalgamer</i>		<t>aim:er</t></v>
<v><i>amancher</i>		<t>aim:er</t></v>
<v><i>amariner</i>		<t>aim:er</t></v>
<v><i>amarrer</i>		<t>aim:er</t></v>
<v><i>amasser</i>		<t>aim:er</t></v>
<v><i>amatir</i>		<t>fin:ir</t></v>
<v><i>ambiancer</i>		<t>pla:cer</t></v>
<v><i>ambitionner</i>		<t>aim:er</t></v>
<v><i>ambler</i>		<t>aim:er</t></v>
<v><i>ambrer</i>		<t>aim:er</t></v>
<v><i>améliorer</i>		<t>aim:er</t></v>
<v><i>aménager</i>		<t>man:ger</t></v>
<v><i>amender</i>		<t>aim:er</t></v>
<v><i>amener</i>		<t>m:ener</t></v>
<v><i>amenuiser</i>		<t>aim:er</t></v>
<v><i>américaniser</i>		<t>aim:er</t></v>
<v><i>amerrir</i>		<t>fin:ir</t></v>
<v><i>ameublir</i>		<t>fin:ir</t></v>
<v><i>ameuter</i>		<t>aim:er</t></v>
<v><i>amidonner</i>		<t>aim:er</t></v>
<v><i>amincir</i>		<t>fin:ir</t></v>
<v><i>amnistier</i>		<t>aim:er</t></v>
<v><i>amocher</i>		<t>aim:er</t></v>
<v><i>amodier</i>		<t>aim:er</t></v>
<v><i>amoindrir</i>		<t>fin:ir</t></v>
<v><i>amollir</i>		<t>fin:ir</t></v>
<v><i>amonceler</i>		<t>app:eler</t></v>
<v><i>amorcer</i>		<t>pla:cer</t></v>
<v><i>amordancer</i>		<t>pla:cer</t></v>
<v><i>amortir</i>		<t>fin:ir</t></v>
<v><i>amouracher</i>		<t>aim:er</t></v>
<v><i>amplifier</i>		<t>aim:er</t></v>
<v><i>amputer</i>		<t>aim:er</t></v>
<v><i>amuïr</i>			<t>amu:ïr</t></v>
<v><i>amurer</i>		<t>aim:er</t></v>
<v><i>amuser</i>		<t>aim:er</t></v>
<v><i>analgésier</i>		<t>aim:er</t></v>
<v><i>analyser</i>		<t>aim:er</t></v>
<v><i>anastomoser</i>		<t>aim:er</t></v>
<v><i>anathématiser</i>		<t>aim:er</t></v>
<v><i>anatomiser</i>		<t>aim:er</t></v>
<v><i>ancrer</i>		<t>aim:er</t></v>
<v><i>anéantir</i>		<t>fin:ir</t></v>
<v><i>anémier</i>		<t>aim:er</t></v>
<v><i>anesthésier</i>		<t>aim:er</t></v>
<v><i>anglaiser</i>		<t>aim:er</t></v>
<v><i>angliciser</i>		<t>aim:er</t></v>
<v><i>angoisser</i>		<t>aim:er</t></v>
<v><i>anhéler</i>		<t>rév:éler</t></v>
<v><i>animaliser</i>		<t>aim:er</t></v>
<v><i>animer</i>		<t>aim:er</t></v>
<v><i>aniser</i>		<t>aim:er</t></v>
<v><i>ankyloser</i>		<t>aim:er</t></v>
<v><i>anneler</i>		<t>app:eler</t></v>
<v><i>annexer</i>		<t>aim:er</t></v>
<v><i>annihiler</i>		<t>aim:er</t></v>
<v><i>annoncer</i>		<t>pla:cer</t></v>
<v><i>annoter</i>		<t>aim:er</t></v>
<v><i>annualiser</i>		<t>aim:er</t></v>
<v><i>annuler</i>		<t>aim:er</t></v>
<v><i>anoblir</i>		<t>fin:ir</t></v>
<v><i>anodiser</i>		<t>aim:er</t></v>
<v><i>ânonner</i>		<t>aim:er</t></v>
<v><i>anordir</i>		<t>fin:ir</t></v>
<v><i>antéposer</i>		<t>aim:er</t></v>
<v><i>anticiper</i>		<t>aim:er</t></v>
<v><i>anticommuter</i>		<t>aim:er</t></v>
<v><i>antidater</i>		<t>aim:er</t></v>
<v><i>antiparasiter</i>		<t>aim:er</t></v>
<v><i>antiquer</i>		<t>aim:er</t></v>
<v><i>aoûter</i>		<t>aim:er</t></v>
<v><i>apaiser</i>		<t>aim:er</t></v>
<v><i>apanager</i>		<t>man:ger</t></v>
<v><i>apercevoir</i>		<t>dé:cevoir</t></v>
<v><i>apeurer</i>		<t>aim:er</t></v>
<v><i>apiquer</i>		<t>aim:er</t></v>
<v><i>apitoyer</i>		<t>netto:yer</t></v>
<v><i>aplanir</i>		<t>fin:ir</t></v>
<v><i>aplatir</i>		<t>fin:ir</t></v>
<v><i>apostasier</i>		<t>aim:er</t></v>
<v><i>aposter</i>		<t>aim:er</t></v>
<v><i>apostiller</i>		<t>aim:er</t></v>
<v><i>apostropher</i>		<t>aim:er</t></v>
<v><i>appairer</i>		<t>aim:er</t></v>
<v><i>apparaître</i>		<t>rep:aître</t></v>
<v><i>appareiller</i>		<t>aim:er</t></v>
<v><i>apparenter</i>		<t>aim:er</t></v>
<v><i>apparier</i>		<t>aim:er</t></v>
<v><i>apparoir</i>		<t>app:aroir</t></v>
<v><i>appartenir</i>		<t>t:enir</t></v>
<v><i>appâter</i>		<t>aim:er</t></v>
<v><i>appauvrir</i>		<t>fin:ir</t></v>
<v><i>appeler</i>		<t>app:eler</t></v>
<v><i>appendre</i>		<t>ten:dre</t></v>
<v><i>appesantir</i>		<t>fin:ir</t></v>
<v><i>applaudir</i>		<t>fin:ir</t></v>
<v><i>appliquer</i>		<t>aim:er</t></v>
<v><i>appointer</i>		<t>aim:er</t></v>
<v><i>appointir</i>		<t>fin:ir</t></v>
<v><i>appondre</i>		<t>ten:dre</t></v>
<v><i>apponter</i>		<t>aim:er</t></v>
<v><i>apporter</i>		<t>aim:er</t></v>
<v><i>apposer</i>		<t>aim:er</t></v>
<v><i>apprécier</i>		<t>aim:er</t></v>
<v><i>appréhender</i>		<t>aim:er</t></v>
<v><i>apprendre</i>		<t>pr:endre</t></v>
<v><i>apprêter</i>		<t>aim:er</t></v>
<v><i>apprivoiser</i>		<t>aim:er</t></v>
<v><i>approcher</i>		<t>aim:er</t></v>
<v><i>approfondir</i>		<t>fin:ir</t></v>
<v><i>approprier</i>		<t>aim:er</t></v>
<v><i>approuver</i>		<t>aim:er</t></v>
<v><i>approvisionner</i>	<t>aim:er</t></v>
<v><i>approximer</i>		<t>aim:er</t></v>
<v><i>appuyer</i>		<t>netto:yer</t></v>
<v><i>apurer</i>		<t>aim:er</t></v>
<v><i>arabiser</i>		<t>aim:er</t></v>
<v><i>araser</i>		<t>aim:er</t></v>
<v><i>arbitrer</i>		<t>aim:er</t></v>
<v><i>arborer</i>		<t>aim:er</t></v>
<v><i>arboriser</i>		<t>aim:er</t></v>
<v><i>arc-bouter</i>		<t>aim:er</t></v>
<v><i>archaïser</i>		<t>aim:er</t></v>
<v><i>architecturer</i>		<t>aim:er</t></v>
<v><i>archiver</i>		<t>aim:er</t></v>
<v><i>arçonner</i>		<t>aim:er</t></v>
<v><i>ardoiser</i>		<t>aim:er</t></v>
<v><i>argenter</i>		<t>aim:er</t></v>
<v><i>arguer</i>		<t>aim:er</t></v>
<v><i>argumenter</i>		<t>aim:er</t></v>
<v><i>ariser</i>		<t>aim:er</t></v>
<v><i>armer</i>			<t>aim:er</t></v>
<v><i>armorier</i>		<t>aim:er</t></v>
<v><i>arnaquer</i>		<t>aim:er</t></v>
<v><i>aromatiser</i>		<t>aim:er</t></v>
<v><i>arpéger</i>		<t>abr:éger</t></v>
<v><i>arpenter</i>		<t>aim:er</t></v>
<v><i>arquer</i>		<t>aim:er</t></v>
<v><i>arracher</i>		<t>aim:er</t></v>
<v><i>arraisonner</i>		<t>aim:er</t></v>
<v><i>arranger</i>		<t>man:ger</t></v>
<v><i>arrenter</i>		<t>aim:er</t></v>
<v><i>arrérager</i>		<t>man:ger</t></v>
<v><i>arrêter</i>		<t>aim:er</t></v>
<v><i>arriérer</i>		<t>réf:érer</t></v>
<v><i>arrimer</i>		<t>aim:er</t></v>
<v><i>arriser</i>		<t>aim:er</t></v>
<v><i>arriver</i>		<t>aim:er</t></v>
<v><i>arroger</i>		<t>man:ger</t></v>
<v><i>arrondir</i>		<t>fin:ir</t></v>
<v><i>arroser</i>		<t>aim:er</t></v>
<v><i>articuler</i>		<t>aim:er</t></v>
<v><i>ascensionner</i>		<t>aim:er</t></v>
<v><i>aseptiser</i>		<t>aim:er</t></v>
<v><i>aspecter</i>		<t>aim:er</t></v>
<v><i>asperger</i>		<t>man:ger</t></v>
<v><i>asphalter</i>		<t>aim:er</t></v>
<v><i>asphyxier</i>		<t>aim:er</t></v>
<v><i>aspirer</i>		<t>aim:er</t></v>
<v><i>assagir</i>		<t>fin:ir</t></v>
<v><i>assaillir</i>		<t>assaill:ir</t></v>
<v><i>assainir</i>		<t>fin:ir</t></v>
<v><i>assaisonner</i>		<t>aim:er</t></v>
<v><i>assarmenter</i>		<t>aim:er</t></v>
<v><i>assassiner</i>		<t>aim:er</t></v>
<v><i>assécher</i>		<t>s:écher</t></v>
<v><i>assembler</i>		<t>aim:er</t></v>
<v><i>asséner</i>		<t>ali:éner</t></v>
<v><i>assener</i>		<t>m:ener</t></v>
<v><i>asseoir</i>		<t>ass:eoir</t></v>
<v><i>assermenter</i>		<t>aim:er</t></v>
<v><i>asservir</i>		<t>fin:ir</t></v>
<v><i>assibiler</i>		<t>aim:er</t></v>
<v><i>assiéger</i>		<t>abr:éger</t></v>
<v><i>assigner</i>		<t>aim:er</t></v>
<v><i>assimiler</i>		<t>aim:er</t></v>
<v><i>assister</i>		<t>aim:er</t></v>
<v><i>associer</i>		<t>aim:er</t></v>
<v><i>assoiffer</i>		<t>aim:er</t></v>
<v><i>assoir</i>		<t>ass:oir</t></v>
<v><i>assoler</i>		<t>aim:er</t></v>
<v><i>assombrir</i>		<t>fin:ir</t></v>
<v><i>assommer</i>		<t>aim:er</t></v>
<v><i>assoner</i>		<t>aim:er</t></v>
<v><i>assortir</i>		<t>fin:ir</t></v>
<v><i>assoupir</i>		<t>fin:ir</t></v>
<v><i>assouplir</i>		<t>fin:ir</t></v>
<v><i>assourdir</i>		<t>fin:ir</t></v>
<v><i>assouvir</i>		<t>fin:ir</t></v>
<v><i>assujettir</i>		<t>fin:ir</t></v>
<v><i>assumer</i>		<t>aim:er</t></v>
<v><i>assurer</i>		<t>aim:er</t></v>
<v><i>asticoter</i>		<t>aim:er</t></v>
<v><i>astiquer</i>		<t>aim:er</t></v>
<v><i>astreindre</i>		<t>crai:ndre</t></v>
<v><i>atermoyer</i>		<t>netto:yer</t></v>
<v><i>atomiser</i>		<t>aim:er</t></v>
<v><i>atrophier</i>		<t>aim:er</t></v>
<v><i>attabler</i>		<t>aim:er</t></v>
<v><i>attacher</i>		<t>aim:er</t></v>
<v><i>attaquer</i>		<t>aim:er</t></v>
<v><i>attarder</i>		<t>aim:er</t></v>
<v><i>atteindre</i>		<t>crai:ndre</t></v>
<v><i>atteler</i>		<t>app:eler</t></v>
<v><i>attendre</i>		<t>ten:dre</t></v>
<v><i>attendrir</i>		<t>fin:ir</t></v>
<v><i>attenter</i>		<t>aim:er</t></v>
<v><i>atténuer</i>		<t>aim:er</t></v>
<v><i>atterrer</i>		<t>aim:er</t></v>
<v><i>atterrir</i>		<t>fin:ir</t></v>
<v><i>attester</i>		<t>aim:er</t></v>
<v><i>attiédir</i>		<t>fin:ir</t></v>
<v><i>attifer</i>		<t>aim:er</t></v>
<v><i>attiger</i>		<t>man:ger</t></v>
<v><i>attirer</i>		<t>aim:er</t></v>
<v><i>attiser</i>		<t>aim:er</t></v>
<v><i>attitrer</i>		<t>aim:er</t></v>
<v><i>attraire</i>		<t>extra:ire</t></v>
<v><i>attraper</i>		<t>aim:er</t></v>
<v><i>attribuer</i>		<t>aim:er</t></v>
<v><i>attriquer</i>		<t>aim:er</t></v>
<v><i>attrister</i>		<t>aim:er</t></v>
<v><i>attrouper</i>		<t>aim:er</t></v>
<v><i>auditer</i>		<t>aim:er</t></v>
<v><i>auditionner</i>		<t>aim:er</t></v>
<v><i>augmenter</i>		<t>aim:er</t></v>
<v><i>augurer</i>		<t>aim:er</t></v>
<v><i>auréoler</i>		<t>aim:er</t></v>
<v><i>aurifier</i>		<t>aim:er</t></v>
<v><i>ausculter</i>		<t>aim:er</t></v>
<v><i>authentifier</i>		<t>aim:er</t></v>
<v><i>authentiquer</i>		<t>aim:er</t></v>
<v><i>autocensurer</i>		<t>aim:er</t></v>
<v><i>autodétruire</i>		<t>condui:re</t></v>
<v><i>autodissoudre</i>		<t>disso:udre</t></v>
<v><i>autofinancer</i>		<t>pla:cer</t></v>
<v><i>autographier</i>		<t>aim:er</t></v>
<v><i>automatiser</i>		<t>aim:er</t></v>
<v><i>autoproclamer</i>		<t>aim:er</t></v>
<v><i>autopsier</i>		<t>aim:er</t></v>
<v><i>autoriser</i>		<t>aim:er</t></v>
<v><i>avachir</i>		<t>fin:ir</t></v>
<v><i>avaler</i>		<t>aim:er</t></v>
<v><i>avaliser</i>		<t>aim:er</t></v>
<v><i>avancer</i>		<t>pla:cer</t></v>
<v><i>avantager</i>		<t>man:ger</t></v>
<v><i>avarier</i>		<t>aim:er</t></v>
<v><i>aventurer</i>		<t>aim:er</t></v>
<v><i>avérer</i>		<t>réf:érer</t></v>
<v><i>avertir</i>		<t>fin:ir</t></v>
<v><i>aveugler</i>		<t>aim:er</t></v>
<v><i>aveulir</i>		<t>fin:ir</t></v>
<v><i>avilir</i>		<t>fin:ir</t></v>
<v><i>aviner</i>		<t>aim:er</t></v>
<v><i>aviser</i>		<t>aim:er</t></v>
<v><i>avitailler</i>		<t>aim:er</t></v>
<v><i>aviver</i>		<t>aim:er</t></v>
<v><i>avoir</i>			<t>:avoir</t></v>
<v><i>avoisiner</i>		<t>aim:er</t></v>
<v><i>avorter</i>		<t>aim:er</t></v>
<v><i>avouer</i>		<t>aim:er</t></v>
<v><i>axer</i>			<t>aim:er</t></v>
<v><i>axiomatiser</i>		<t>aim:er</t></v>
<v><i>azorer</i>		<t>aim:er</t></v>
<v><i>azurer</i>		<t>aim:er</t></v>
<v><i>babiller</i>		<t>aim:er</t></v>
<v><i>baboler</i>		<t>aim:er</t></v>
<v><i>bâcher</i>		<t>aim:er</t></v>
<v><i>bachoter</i>		<t>aim:er</t></v>
<v><i>bâcler</i>		<t>aim:er</t></v>
<v><i>badauder</i>		<t>aim:er</t></v>
<v><i>bader</i>			<t>aim:er</t></v>
<v><i>badger</i>		<t>man:ger</t></v>
<v><i>badigeonner</i>		<t>aim:er</t></v>
<v><i>badiner</i>		<t>aim:er</t></v>
<v><i>baffer</i>		<t>aim:er</t></v>
<v><i>bafouer</i>		<t>aim:er</t></v>
<v><i>bafouiller</i>		<t>aim:er</t></v>
<v><i>bâfrer</i>		<t>aim:er</t></v>
<v><i>bagarrer</i>		<t>aim:er</t></v>
<v><i>baguenauder</i>		<t>aim:er</t></v>
<v><i>baguer</i>		<t>aim:er</t></v>
<v><i>baigner</i>		<t>aim:er</t></v>
<v><i>bailler</i>		<t>aim:er</t></v>
<v><i>bâiller</i>		<t>aim:er</t></v>
<v><i>bâillonner</i>		<t>aim:er</t></v>
<v><i>baiser</i>		<t>aim:er</t></v>
<v><i>baisoter</i>		<t>aim:er</t></v>
<v><i>baisser</i>		<t>aim:er</t></v>
<v><i>balader</i>		<t>aim:er</t></v>
<v><i>balafrer</i>		<t>aim:er</t></v>
<v><i>balancer</i>		<t>pla:cer</t></v>
<v><i>balayer</i>		<t>pa:yer</t></v>
<v><i>balbutier</i>		<t>aim:er</t></v>
<v><i>baleiner</i>		<t>aim:er</t></v>
<v><i>baliser</i>		<t>aim:er</t></v>
<v><i>balkaniser</i>		<t>aim:er</t></v>
<v><i>ballaster</i>		<t>aim:er</t></v>
<v><i>baller</i>		<t>aim:er</t></v>
<v><i>ballonner</i>		<t>aim:er</t></v>
<v><i>ballotter</i>		<t>aim:er</t></v>
<v><i>bambocher</i>		<t>aim:er</t></v>
<v><i>banaliser</i>		<t>aim:er</t></v>
<v><i>bancher</i>		<t>aim:er</t></v>
<v><i>bander</i>		<t>aim:er</t></v>
<v><i>banner</i>		<t>aim:er</t></v>
<v><i>bannir</i>		<t>fin:ir</t></v>
<v><i>banquer</i>		<t>aim:er</t></v>
<v><i>banqueter</i>		<t>j:eter</t></v>
<v><i>baptiser</i>		<t>aim:er</t></v>
<v><i>baqueter</i>		<t>j:eter</t></v>
<v><i>baragouiner</i>		<t>aim:er</t></v>
<v><i>baraquer</i>		<t>aim:er</t></v>
<v><i>baratiner</i>		<t>aim:er</t></v>
<v><i>baratter</i>		<t>aim:er</t></v>
<v><i>barber</i>		<t>aim:er</t></v>
<v><i>barbifier</i>		<t>aim:er</t></v>
<v><i>barboter</i>		<t>aim:er</t></v>
<v><i>barbouiller</i>		<t>aim:er</t></v>
<v><i>barder</i>		<t>aim:er</t></v>
<v><i>baréter</i>		<t>décr:éter</t></v>
<v><i>barguigner</i>		<t>aim:er</t></v>
<v><i>barioler</i>		<t>aim:er</t></v>
<v><i>barjaquer</i>		<t>aim:er</t></v>
<v><i>baronner</i>		<t>aim:er</t></v>
<v><i>barouder</i>		<t>aim:er</t></v>
<v><i>barrer</i>		<t>aim:er</t></v>
<v><i>barricader</i>		<t>aim:er</t></v>
<v><i>barrir</i>		<t>fin:ir</t></v>
<v><i>basaner</i>		<t>aim:er</t></v>
<v><i>basculer</i>		<t>aim:er</t></v>
<v><i>baser</i>			<t>aim:er</t></v>
<v><i>bassiner</i>		<t>aim:er</t></v>
<v><i>baster</i>		<t>aim:er</t></v>
<v><i>bastillonner</i>		<t>aim:er</t></v>
<v><i>bastionner</i>		<t>aim:er</t></v>
<v><i>batailler</i>		<t>aim:er</t></v>
<v><i>bateler</i>		<t>app:eler</t></v>
<v><i>bâter</i>			<t>aim:er</t></v>
<v><i>batifoler</i>		<t>aim:er</t></v>
<v><i>bâtir</i>			<t>fin:ir</t></v>
<v><i>batoiller</i>		<t>aim:er</t></v>
<v><i>bâtonner</i>		<t>aim:er</t></v>
<v><i>battre</i>		<t>bat:tre</t></v>
<v><i>bauger</i>		<t>man:ger</t></v>
<v><i>bavarder</i>		<t>aim:er</t></v>
<v><i>bavasser</i>		<t>aim:er</t></v>
<v><i>baver</i>			<t>aim:er</t></v>
<v><i>bavocher</i>		<t>aim:er</t></v>
<v><i>bayer</i>			<t>pa:yer</t></v>
<v><i>bazarder</i>		<t>aim:er</t></v>
<v><i>béatifier</i>		<t>aim:er</t></v>
<v><i>bêcher</i>		<t>aim:er</t></v>
<v><i>bêcheveter</i>		<t>j:eter</t></v>
<v><i>bécoter</i>		<t>aim:er</t></v>
<v><i>becquer</i>		<t>aim:er</t></v>
<v><i>becqueter</i>		<t>j:eter</t></v>
<v><i>becter</i>		<t>aim:er</t></v>
<v><i>bedonner</i>		<t>aim:er</t></v>
<v><i>bégayer</i>		<t>pa:yer</t></v>
<v><i>bégueter</i>		<t>ach:eter</t></v>
<v><i>bêler</i>			<t>aim:er</t></v>
<v><i>bémoliser</i>		<t>aim:er</t></v>
<v><i>bénéficier</i>		<t>aim:er</t></v>
<v><i>bénir</i>			<t>fin:ir</t></v>
<v><i>béqueter</i>		<t>j:eter</t></v>
<v><i>béquiller</i>		<t>aim:er</t></v>
<v><i>bercer</i>		<t>pla:cer</t></v>
<v><i>berner</i>		<t>aim:er</t></v>
<v><i>besogner</i>		<t>aim:er</t></v>
<v><i>bêtifier</i>		<t>aim:er</t></v>
<v><i>bêtiser</i>		<t>aim:er</t></v>
<v><i>bétonner</i>		<t>aim:er</t></v>
<v><i>beugler</i>		<t>aim:er</t></v>
<v><i>beurrer</i>		<t>aim:er</t></v>
<v><i>biaiser</i>		<t>aim:er</t></v>
<v><i>bibeloter</i>		<t>aim:er</t></v>
<v><i>biberonner</i>		<t>aim:er</t></v>
<v><i>bicher</i>		<t>aim:er</t></v>
<v><i>bichonner</i>		<t>aim:er</t></v>
<v><i>bichoter</i>		<t>aim:er</t></v>
<v><i>bidonner</i>		<t>aim:er</t></v>
<v><i>bidouiller</i>		<t>aim:er</t></v>
<v><i>biffer</i>		<t>aim:er</t></v>
<v><i>bifurquer</i>		<t>aim:er</t></v>
<v><i>bigarrer</i>		<t>aim:er</t></v>
<v><i>bigler</i>		<t>aim:er</t></v>
<v><i>bigophoner</i>		<t>aim:er</t></v>
<v><i>bigorner</i>		<t>aim:er</t></v>
<v><i>biler</i>			<t>aim:er</t></v>
<v><i>billebauder</i>		<t>aim:er</t></v>
<v><i>biller</i>		<t>aim:er</t></v>
<v><i>billonner</i>		<t>aim:er</t></v>
<v><i>biloquer</i>		<t>aim:er</t></v>
<v><i>biner</i>			<t>aim:er</t></v>
<v><i>biscuiter</i>		<t>aim:er</t></v>
<v><i>biseauter</i>		<t>aim:er</t></v>
<v><i>bisegmenter</i>		<t>aim:er</t></v>
<v><i>biser</i>			<t>aim:er</t></v>
<v><i>bisquer</i>		<t>aim:er</t></v>
<v><i>bisser</i>		<t>aim:er</t></v>
<v><i>bistourner</i>		<t>aim:er</t></v>
<v><i>bistrer</i>		<t>aim:er</t></v>
<v><i>biter</i>			<t>aim:er</t></v>
<v><i>bitter</i>		<t>aim:er</t></v>
<v><i>bitturer</i>		<t>aim:er</t></v>
<v><i>bitumer</i>		<t>aim:er</t></v>
<v><i>bituminer</i>		<t>aim:er</t></v>
<v><i>biturer</i>		<t>aim:er</t></v>
<v><i>bivouaquer</i>		<t>aim:er</t></v>
<v><i>bizuter</i>		<t>aim:er</t></v>
<v><i>blablater</i>		<t>aim:er</t></v>
<v><i>blackbouler</i>		<t>aim:er</t></v>
<v><i>blaguer</i>		<t>aim:er</t></v>
<v><i>blairer</i>		<t>aim:er</t></v>
<v><i>blâmer</i>		<t>aim:er</t></v>
<v><i>blanchir</i>		<t>fin:ir</t></v>
<v><i>blaser</i>		<t>aim:er</t></v>
<v><i>blasonner</i>		<t>aim:er</t></v>
<v><i>blasphémer</i>		<t>cr:émer</t></v>
<v><i>blatérer</i>		<t>réf:érer</t></v>
<v><i>blêmir</i>		<t>fin:ir</t></v>
<v><i>bléser</i>		<t>l:éser</t></v>
<v><i>blesser</i>		<t>aim:er</t></v>
<v><i>blettir</i>		<t>fin:ir</t></v>
<v><i>bleuir</i>		<t>fin:ir</t></v>
<v><i>bleuter</i>		<t>aim:er</t></v>
<v><i>blinder</i>		<t>aim:er</t></v>
<v><i>blinquer</i>		<t>aim:er</t></v>
<v><i>blondir</i>		<t>fin:ir</t></v>
<v><i>blondoyer</i>		<t>netto:yer</t></v>
<v><i>bloquer</i>		<t>aim:er</t></v>
<v><i>blottir</i>		<t>fin:ir</t></v>
<v><i>blouser</i>		<t>aim:er</t></v>
<v><i>bluffer</i>		<t>aim:er</t></v>
<v><i>bluter</i>		<t>aim:er</t></v>
<v><i>bobiner</i>		<t>aim:er</t></v>
<v><i>bocarder</i>		<t>aim:er</t></v>
<v><i>boetter</i>		<t>aim:er</t></v>
<v><i>boire</i>			<t>b:oire</t></v>
<v><i>boiser</i>		<t>aim:er</t></v>
<v><i>boiter</i>		<t>aim:er</t></v>
<v><i>boitiller</i>		<t>aim:er</t></v>
<v><i>bolchéviser</i>		<t>aim:er</t></v>
<v><i>bombarder</i>		<t>aim:er</t></v>
<v><i>bomber</i>		<t>aim:er</t></v>
<v><i>bondériser</i>		<t>aim:er</t></v>
<v><i>bonder</i>		<t>aim:er</t></v>
<v><i>bondir</i>		<t>fin:ir</t></v>
<v><i>bondonner</i>		<t>aim:er</t></v>
<v><i>bonifier</i>		<t>aim:er</t></v>
<v><i>bonimenter</i>		<t>aim:er</t></v>
<v><i>border</i>		<t>aim:er</t></v>
<v><i>borner</i>		<t>aim:er</t></v>
<v><i>bornoyer</i>		<t>netto:yer</t></v>
<v><i>bosseler</i>		<t>app:eler</t></v>
<v><i>bosser</i>		<t>aim:er</t></v>
<v><i>bossuer</i>		<t>aim:er</t></v>
<v><i>bostonner</i>		<t>aim:er</t></v>
<v><i>botaniser</i>		<t>aim:er</t></v>
<v><i>botteler</i>		<t>app:eler</t></v>
<v><i>botter</i>		<t>aim:er</t></v>
<v><i>boubouler</i>		<t>aim:er</t></v>
<v><i>boucaner</i>		<t>aim:er</t></v>
<v><i>boucharder</i>		<t>aim:er</t></v>
<v><i>boucher</i>		<t>aim:er</t></v>
<v><i>bouchonner</i>		<t>aim:er</t></v>
<v><i>bouchoyer</i>		<t>netto:yer</t></v>
<v><i>boucler</i>		<t>aim:er</t></v>
<v><i>bouder</i>		<t>aim:er</t></v>
<v><i>boudiner</i>		<t>aim:er</t></v>
<v><i>bouéler</i>		<t>rév:éler</t></v>
<v><i>bouffer</i>		<t>aim:er</t></v>
<v><i>bouffir</i>		<t>fin:ir</t></v>
<v><i>bouffonner</i>		<t>aim:er</t></v>
<v><i>bouger</i>		<t>man:ger</t></v>
<v><i>bougonner</i>		<t>aim:er</t></v>
<v><i>bouillir</i>		<t>bou:illir</t></v>
<v><i>bouillonner</i>		<t>aim:er</t></v>
<v><i>bouillotter</i>		<t>aim:er</t></v>
<v><i>boulanger</i>		<t>man:ger</t></v>
<v><i>bouléguer</i>		<t>l:éguer</t></v>
<v><i>bouler</i>		<t>aim:er</t></v>
<v><i>bouleverser</i>		<t>aim:er</t></v>
<v><i>boulocher</i>		<t>aim:er</t></v>
<v><i>boulonner</i>		<t>aim:er</t></v>
<v><i>boulotter</i>		<t>aim:er</t></v>
<v><i>boumer</i>		<t>aim:er</t></v>
<v><i>bouquiner</i>		<t>aim:er</t></v>
<v><i>bourasser</i>		<t>aim:er</t></v>
<v><i>bourder</i>		<t>aim:er</t></v>
<v><i>bourdonner</i>		<t>aim:er</t></v>
<v><i>bourgeonner</i>		<t>aim:er</t></v>
<v><i>bourlinguer</i>		<t>aim:er</t></v>
<v><i>bouronner</i>		<t>aim:er</t></v>
<v><i>bourreler</i>		<t>app:eler</t></v>
<v><i>bourrer</i>		<t>aim:er</t></v>
<v><i>bourriquer</i>		<t>aim:er</t></v>
<v><i>boursicoter</i>		<t>aim:er</t></v>
<v><i>boursoufler</i>		<t>aim:er</t></v>
<v><i>bousculer</i>		<t>aim:er</t></v>
<v><i>bousiller</i>		<t>aim:er</t></v>
<v><i>boustifailler</i>		<t>aim:er</t></v>
<v><i>bouter</i>		<t>aim:er</t></v>
<v><i>boutonner</i>		<t>aim:er</t></v>
<v><i>bouturer</i>		<t>aim:er</t></v>
<v><i>boxer</i>			<t>aim:er</t></v>